### ISSUE TITLE
Fragments should be selected before choosing the right label 

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#111]
```yaml
Type: Ergonomy fix
Difficulty: Low
```

#### Current scenario
1. The reader finds an interesting fragment in the interview transcript.
2. She goes to the bottom menu and types the label (aka _code_) in the text box.
3. She goes back to the interview transcript and search for the fragment.
4. She selects the fragment.
5. She goes to the bottom menu and pushes the label creation button.

#### Suggested scenario
1. The reader finds an interesting fragment in the interview transcript and select it.
2. She goes to the bottom menu and pushes the label creation button.
3. She types the label (aka _code_) in the text box of a dialog.

**Comment by christophe-lejeune** [comment]
According to me both scenarii are already supported by the software.

**Comment by benel** [comment]
Maybe my explanation was not precise enough. But the result is indeed different.

https://user-images.githubusercontent.com/597307/143222666-848aca84-9da4-4df6-bc40-0dde9d685a81.mov

**Comment by christophe-lejeune** [comment]
I apology, I did not understand, indeed. Obviously, In this example, one does not get what is intended. 

This behavior is intended for (untyped) legacy field memos. Here, the layout (with speaker in bold font) suggests this field memo is a legacy (untyped) one. Yet, the fragment coding feature was designed for interview-typed memos.

To enable this feature, this legacy (untyped) memo should be converted into interview. Such a conversion is automatic if you simply edit the memo. Be patient, the conversion could take time. After this conversion, fragments coding will be available.

**Comment by benel** [comment]
Great. I confirm that after converting the memo, it now works.
<img width="1255" alt="Capture d’écran 2021-11-24 à 12 07 37" src="https://user-images.githubusercontent.com/597307/143227519-a1d5b244-2e84-45bd-9e34-4d7bde1d2900.png">

**Comment by benel** [comment]
Weird, I have the same problem again... Maybe because I've updated with master ?

**Comment by benel** [comment]
I'm lost... Could you test it yourself? I've given the rights to do it on [the transcript](https://cassandre.utt.fr/memo/f413206cef01d9b99ebb3b6de200726d/edbb69a33827773d728069d87556d2e7)...

**Comment by christophe-lejeune** [comment]
As you indicated in a personal communication, Cassandre behave differently according to the way the coding is entered (through the button or by hitting `enter`). Commit e81a08a072aa338e830d058e6054c24e5f240ff6 ensures that both strategies produce the same result. 

Thank you very much for your feedback !

**Comment by benel** [comment]
Thank you for the fix!

**Comment by christophe-lejeune** [comment]
Thank you very much for your feedback !

Indeed, the selection is stored (in the search box) so that it remains available when the focus changes (when the user types the name of the code/coding memo).

The issue you're mentioning is about visual cue, while previous fixes were about different versions of the interview transcript and about the creation of the coding memo (with a button or enter). Let's open another ticket, if you do not mind ;-)
