### ISSUE TITLE
Reusing a label to "code" a fragment should be easier

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#112]
```yaml
Type: Ergonomy fix
Difficulty: Medium
```

#### Current scenario

1. The analyst types the exact name of an existing label (_aka_ code).
2. She confirms that she wants to reuse the existing label.

#### Suggested scenario

1. The analyst can choose an existing label (or type a new one).
2. If she has choosed to reuse an existing label, she don't have to confirm anything.

**Comment by christophe-lejeune** [comment]
This "fix" facilitates and fosters tagging/coding. From a pure QDA point of view, this seems desirable. 

However, from the point of view of a person teaching qualitative research and reflexivity, this is questionable. CAQDAS facilitates tagging (though code-and-retrieve features). Software users often become overwhelmed with tags/codes. Some of them even turn away from software for this reason. 

For some researchers (as Barney Glaser), this issue motivates to focus on writing memos (for him, codes "just occur in the analyst's head"). On the other end, Suzanne Friese maintains that tagging/coding helps the researcher (tagging for organizational reasons; coding for methodological ones). 

Cassandre's architecture supports both strategies: either direct memoing or tagging/coding-cum-memoing. I am not opposed to disable the warning prompt, but we should be aware that it was introduced for good methodological reasons.

**Comment by benel** [comment]
> I am not opposed to disable the warning prompt, but we should be aware that it was introduced for good methodological reasons.

Hmm... OK... So is it a yes or a no? ;)

**Comment by christophe-lejeune** [comment]
The requested behavior is implemented. As indicated in 8e0a7208250788d6366692bc3aeeffa579d4b4a2 commit message, it is currently reserved to field memos and transcripts. Do not hesitate to ask to expand it to other type of memos, if you think it is relevant.

**Comment by benel** [comment]
Weird. It worked. But I upgraded a few weeks ago and it doesn't work anymore. I will try to update to the latest version.

**Comment by benel** [comment]
Thank you very much for this ergonomy fix.
