### ISSUE TITLE
Markdown markup should stay invisible in Anchors snippets

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#123]
Reproduction scenario:

1. Create the following (coding) memo:
```
On remarque que les actions sont principalement de deux ordres : 
- celles liées à la matérialité de la fouille, de la terre, des vestiges ([décaper](edbb69a33827773d728069d87556d2e7#15), [creuser](edbb69a33827773d728069d87556d2e7#15), [tamiser](edbb69a33827773d728069d87556d2e7#9), [prélever](edbb69a33827773d728069d87556d2e7#19), nettoyer, [mettre en sac](edbb69a33827773d728069d87556d2e7#15), étiqueter), 
- celles liées à la production de documents (faire le relevé, [photographier](edbb69a33827773d728069d87556d2e7#15), [dessiner les plans](edbb69a33827773d728069d87556d2e7#15), rédiger).
``` 
2. Based on the current memo, create a new (theoretical) memo.
3. Show the anchors. 
4. The result is:
<img width="284" alt="Capture d’écran 2022-10-14 à 10 54 49" src="https://user-images.githubusercontent.com/597307/195806245-3a7cc677-2564-45d7-9995-88c5fbb97731.png">

Instead it should be:
```
On remarque que les actions sont principalement de deux ordres :
- celles liées à la matérialité de la fouille, de la terre, des vestiges (décaper, creuser, tam
```

I suppose we can either: 
- filter out every Markdown markup (but we won't see picture anymore, style, etc.),
- cut out the string inside the markup but not the markup itself,
- filter out all links (they don't seems to be necessary here since they are a sort of a link within a link).

For the first two options, extensive tests should be done to be sure not to break anything with this fix...
The third one seems to have less potential side effects (just be sure not to filter out images which code is similar in Markdown).

**Comment by christophe-lejeune** [comment]
Thank you very much @benel for reporting this issue !

Such a phenomenon occurs not only with links but any "truncated" markup (underline, bold, italic). Moreover, the `nested links' (link inside link) issue concerns not only previews, but also (diary and user) activity. A quick fix is currently being tested (see branch issue-123). It will be merge into master after further tests.
