### ISSUE TITLE
XML export should preserve paragraphs

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#135]
Well done for your exports @christophe-lejeune!
I had not seen the new version of them (export by diary rather than by memo), and the new version is really cool. 🥇 

Personally I will use JSON, but if someone prefer XML I suppose (s)he will have problems with paragraphs in memo.
XML parsers don't (necessarily) preserve new lines.

You could either use an **element that wraps the paragraph** or an **empty element as a separator**. Of course, you could name them as you like.

For example if you decide to use well-known elements `br` or `p` from HTML , this could be coded either as:

```js
text.split('\n\n').join('<br/>')
```

or:

```js
text.split('\n\n').map(x => `<p>${x}</p>`).join()
```

Just my two cents if there are still people using XML 😉

**Comment by christophe-lejeune** [comment]
Thank you very much for your feedback, @benel ! 

This (minor) refactoring will be published soon. The code slightly differs from what you suggest. Using `replace` with a regular expression, it is (a bit) less elegant, but allows to manage some cases that the `split`/`join` way overlooks. 

Many thanks for this (additional) contribution to Cassandre source code !!!
