### ISSUE TITLE
"Select all" doesn't always select.

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#39]
Reproduction scenario:
- Open `/text`
- Click on `Create...`
- Fill title with `FOO`
- Fill corpus with `BAR`
- Save
- Save
- Click on `BAR`
- Click on `Delete...`
- Check `Select all`
- Uncheck  `Select all`
- Check `Select all`
- `Foo` is not checked :’-(
- Click on `Delete...`
- `Foo` is still there :’-(

**Comment by christophe-lejeune** [comment]
I confirm the problem still occur when deleting memos from a diary (this is the same code).

**Comment by benel** [comment]
> I confirm the problem still occur when deleting memos from a diary (this is the same code).
> 
On `click` `#toggle`, try replacing ˋattr` with ˋprop`.

**Comment by christophe-lejeune** [comment]
Great. This indeed works really better.
