### ISSUE TITLE
Rédiger un compte-rendu

### ISSUE THREAD

**Issue by bj0rge** [Hypertopic/Cassandre#40]
# Summary of required features
- [x] Create a memo.
- [x] Edit a memo.
  - [x] Memo includes Markdown Layout.
  - [x] Link to online pictures (thanks to Markdown)
  - [ ] Upload a picture to a memo.
    - [ ] Same as above (with drag and drop).
- [ ] Delete the picture attached to a memo.
- [x] Delete a memo.
# Discussion

_Issue created with @yeahger & @valentinlefevre_

We try and synthesized the scenario 'writing a memo'. The different steps we were able to identify are the following:
- Writing the date
- Writing the place & context
- Writing down the first impressions & notes
- Transcribe the interview
- Labeling the interview
- Naming the hole memo for referencing it
- Join meeting review & own notes
- Transcribe the decisions taken during the meeting

We also understood the need about anchors which is a central feature in the activity of writing a memo.

**Comment by EdwardNjango** [comment]
Les différents types de compte-rendu : 

![img_20150330_165223](https://cloud.githubusercontent.com/assets/10283167/6899296/d01f89a6-d6ff-11e4-83df-d457471c5e28.jpg)

**Comment by PabloPrudhommeau** [comment]
According to the feature #41, we think about including some additionnal features during writing a memo 
- We can associate a piece of text to a tag (For instance : "Personnal notes" or "Behaviour manifestation")
- These tags can be created by two differents ways
  - With a specific syntax (For instance "\PersonnalNotes{I think he is trying to explain that it was a hard part of his life}")
  - With a WYSIWYG editor

**Comment by AndreMarvell** [comment]
@christophe-lejeune, pour rebondir sur la question des types de formulaires lors de la création d'un mémo : Les informations fournies dans les types de comptes rendu sont elles differentes au point d'avoir besoin de formulaires distincts pour chacun d'eux ?

**Comment by christophe-lejeune** [comment]
If you refers to the page 30 of the Handbook, you can see that every memo has the same structure and attributes. This advocates for same (or similar) form. 

Every memo requires :
* the name of the project : could be the name of the project, or the content of another (theoretical) memo
* a type : to be picked in a closed list
* a date : could be automatically inserted
* an author : the name/id of the user that writes the memo (in some case, multiple authors could be allowed).
* a title
* a grounding : the reference of a memo previously written. 
* a body : the content (text or schema) written by the user.

**Comment by AndreMarvell** [comment]
Thanks @christophe-lejeune. Knowing that every memo has the same structure, so we will choose the first approach : Only one form with different headings for each type of the memo.

**Comment by christophe-lejeune** [comment]
Some details : 
* Be sure not to confuse headers (mentioning "fixed" information such as author and date) and tags (which contains interpretation different from one user to another). 
* Here under is the English version of the diadram mentioned above 
![memo-overall_2](https://cloud.githubusercontent.com/assets/619124/6981338/ceca536c-d9ff-11e4-92a0-3a2b62725b80.png)

**Comment by mchidaine** [comment]
Here we have 2 mockups : 
- one showing the field note with its tags on one side with the option to add a code note related to this field note;
- one showing the creation of a new code note once we've clicked on the "add a code note" button

We chose to link the different types of memos by directly having the option to create a memo from another memo; since they're all created in a logical order, it seemed more interesting to link them this way.

![](https://utt.mybalsamiq.com/mockups/2981319.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)
![](https://utt.mybalsamiq.com/mockups/2981302.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

**Comment by christophe-lejeune** [comment]
It took me a little time to understand the mock-ups. Now it is becoming clear. 

Some comments, to stimulate our discussion

* The content of the field note (on the first mock-up) looks a bit strange. A field note contains usually observation notes or interview transcript. 

* The GUI of the second mock-up assumes that code notes have something to do with [LaSuli](https://github.com/Hypertopic/LaSuli). Well, this makes sense given that LaSuli is a **coding** add-on and that code notes are related to **coding**. However, don't you think that some users could be willing to fill some code notes without going though LaSuli?

* When I hit "add a code note", is the created code note linked directly to the original field note, or to the highlighted text, or to one of the code featured in LaSuli ? What if I do not select any element before hitting the button? 

* The second mock-up is a creation panel. Will the same panel be used to edit the memo? If it is the case, how can the user see the link with other memos? In such a case, will the creation date be replaced by the edit date? For instance, [Weft-QDA](http://www.pressure.to/qda/) keeps two date (creation and last edit).

**Comment by PabloPrudhommeau** [comment]
As we said during the meetup this morning between Aurelien Benel and the friday TP's group, we finally  concluded that it would be a good idea to build a software which includes the functionnalities of LaSuli but doesn't require the Firefox extension itself. 
On the basis of @mchidaine's mock-up, we tried to complete it in adding some functionnalities previously mentionned by @christophe-lejeune in https://github.com/Hypertopic/Cassandre/issues/40#issuecomment-90950304.
We have begun two mock-ups, and we need to know if its represent more respectively the work of writing a coding memo.
![Writing a memo](https://utt.mybalsamiq.com/mockups/2993271.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)
![Writing a coding memo](https://utt.mybalsamiq.com/mockups/2993288.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)
These two mock-ups need to be continued and completed.

**Comment by valentin-bonino** [comment]
@salamata and I worked on a form to create memos. In the mock up we made, we create a new field note, where we can fill in the authors, the title of the memo and the body. But the same type of form can be used for other types of note. There is no selection of type, because "create a new memo" button will be on the previous memo.

![creer un compte-rendu de terrain](https://cloud.githubusercontent.com/assets/7694366/7119702/ee776e1a-e207-11e4-9f9f-9d0b1b29476f.jpeg)

**Comment by PabloPrudhommeau** [comment]
@valentin-bonino, you obviously didn't see what we said in https://github.com/Hypertopic/Cassandre/issues/40#issuecomment-91518124. Indeed we made a check-up with @benel the last friday (April, 10th), and we talked about two main things : 
- The **functionnalities** of LaSuli have to be included in cassandre 2, and cassandre doesn't have to require the "LaSuli" firefox extension anymore. In your mock-up, it's appear that you didn't consider this point.
- The second point is the coding memo that doesn't appear too in your mock-up.
Please, if there are some points to clarify (mock-ups, the way we see things, etc..), please post a comment before creating a new mock-up.

**Comment by PabloPrudhommeau** [comment]
@christophe-lejeune, we have difficulties to understand where the properties of the coding memo come from (ref 4.1.1). Are they keywords previously highlighted in the memo (with LaSuli functionalities) ? Globally, we didn't understand where the column and row names come from (Example : Mathieu (motos) for the row, and "Oser expérimenter" for the column)

**Comment by salamata** [comment]
OK! It was just the first mockup version 1.0. We are going to change it and considerer your comment. I didn't know that we have to use lasuli with the memo.

**Comment by christophe-lejeune** [comment]
Not allowing to pick the memo type is a good idea. I see at least two benefits. 
* It "forces" the user to choose a type when hitting the button. 
* By doing so, we also avoid untyped memos. 

However, when rethinking about your mock-ups, be aware of the following : 
* Both a code note and a theoretical note can be grounded in a code note, for instance. Thus, more than one button have to be provided from the memo page (depending on its type). Check the diagram above, to review all possible follow-up type (and, thus, all needed buttons). 
* While a code note is basically grounded in only one memo (either a field note or a code note), theoretical notes are mainly based on more than one memo (theoretical notes are used for comparison). The theoretical note could also be created through a button, but the interface need to allow to add additional groundings.

NB: Perhaps another issue could be dedicated on mock-ups to read memo, given the edit window will be slightly different.

**Comment by EdwardNjango** [comment]
Un mémo pouvant pointer vers plusieurs types de mémos (ex: compte-rendu théorique vers compte-rendu opérationnel, analytique et schématisation), l'ajout de nouveaux mémos à partir d'un précédent doit permettre de choisir le type. Je propose d'illustrer ce cas particulier par la maquette suivante.

![maquette](https://utt.mybalsamiq.com/mockups/3028964.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

**Comment by ConstantSIDJUI** [comment]
Etant donnée que l'affichage se fait en parallèle comme précisé dans le ticket #41 lors de la navigation il doit y avoir une précision sur le choix du mémos lorsqu'il y a plusieurs alternatives. exemple sur la figure ci-dessous illustre un cas de navigation lorsque nous somme au niveau du mémo: Compte rendu théorique (Th), nous pouvons naviguer soit vers le mémo: Compte-rendu Opérationnel (O), soit vers le mémo: Schématisation (S). dans la figure nous avons choisit de faire une navigation sur la Schématisation (à droite de la figure) et  l'affichage précise les deux compte-rendus Théoriques sous lesquels la Schématisation est ancré.

![11178538_861412693919364_201684130_n](https://cloud.githubusercontent.com/assets/11837102/7246459/391f30e6-e7fe-11e4-8114-c096de0711bb.jpg)

Légende:
C = Compte-rendu de codage
Th = Compte-rendu de Théorique
O = Compte-rendu de opérationnel
S = Shématisation

**Comment by ConstantSIDJUI** [comment]
![11146011_861413593919274_2038201557_n](https://cloud.githubusercontent.com/assets/11837102/7246726/55d4dde6-e801-11e4-9d77-6c574264f732.jpg)



La figure ci-dessus représente une maquette pour l'ajout d'un mémo car cela devient ambigu lorsqu'on se situe au niveau du compte-rendu Théorique (Th) et de la Schématisation (S). Etant sur un compte-rendu Théorique (Th) on doit pouvoir ajouter une Schématisation. Une foi la Schématisation ajoutée et étant donnée qu'une schématisation est ancrée sur deux compte-rendu Théorique alors on doit pouvoir ajouter le second compte-rendu théorique sur lequel il est ancré ce qui explique le module en dessous du compte-rendu Théorique après l'ajout d'une Schématisation.

Légende:
C = Compte-rendu de codage
Th = Compte-rendu de Théorique
S = Shématisation

**Comment by christophe-lejeune** [comment]
Afin que nous soyons sûrs de nous comprendre, puis-je vous demander de relire vos deux dernières contributions, d'en corriger l'orthohgraphe ainsi que la ponctuation ?

**Comment by christophe-lejeune** [comment]
Si je comprends bien,
* https://github.com/Hypertopic/Cassandre/issues/40#issuecomment-94652330 concerne la navigation
* https://github.com/Hypertopic/Cassandre/issues/40#issuecomment-94654263 concerne la création d'un compte-rendu.

Si c'est bien cela, alors la première maquette relèverait plutôt du #47 (et n'a donc pas sa place ici). Corrigez-moi si je me trompe. 

Je ne suis pas certain de mesurer l'apport de la partie gauche de cette première maquette, pour deux raisons. 
* La liste des comptes-rendus sur lesquels s'appuie un compte-rendu est présente dans l'entête. Ne suffit-il pas de cliquer sur celui qui nous intéresse pour s'y rendre ? 
* Afficher les comptes-rendus sur lesquels s'appuie un compte-rendu est certes aisé, dans cet exemple, où 2 comptes-rendus sont concernés. Lorsqu'il seront 10, cet affichage ne risque-t-il pas de devenir plus compliqué ?

En ce qui concerne la deuxième maquette, le module sous le compte-rendu théorique de la partie gauche me semble effectivement constituer une bonne solution. On peut cependant se demander, à nouveau, s'il ne suffirait pas, de permettre les ajouts dans le champ "Ancrage" de l'entête, grâce à un bouton [ + ] (comme on le ferait pour les auteurs).

**Comment by Yeahger** [comment]
# Synthèse de la rédaction d'une entrée dans le journal de bord

Le mot "mémo" entraîne des confusions. On devrait donc plutôt parler "d'entrée dans le journal de bord". Cette entrée est typée d'après le schéma disponible dans  https://github.com/Hypertopic/Cassandre/issues/40#issuecomment-87717922.

À l'exception de la première entrée du journal qui sera un compte-rendu de terrain indépendant, les autres entrées seront ancrées à une ou plusieurs autres entrées.
Au niveau de l'affichage, l'écran sera divisé en deux : 
  - à gauche : une vision des documents sur lequel est ancrée l'entrée (vide pour le premier compte-rendu de terrain)
  - à droite : la nouvelle entrée à rédiger

La rédaction d'un compte-rendu sera dépendante du type d'entrée que l'on souhaite rédiger.
- Saisie de texte
- Questions / réponses pour le compte-rendu de terrain
- Système de marqueurs "Lasuli" pour l’étiquetage
- Diagrammes 
  - soit upload de document
  - soit éditeur de diagramme

**Comment by christophe-lejeune** [comment]
Merci pour cette très bonne synthèse qui va à l'essentiel. Je ne vois rien à objecter à ce qu'elle contient. 

Je me permets juste de compléter la liste des modalités de rédaction des comptes-rendus.
* Pour les **diagrammes**, un éditeur présenterait plusieurs avantages sur l'importation d'images : 
 * Les utilisateurs pourraient choisir les noms des nœuds parmi les étiquettes déjà créés. Ainsi les *ancrages* des diagrammes se compléteraient automatiquement.  
 * En outre, ce faisant, cliquer sur les nœuds du diagramme permettrait d'aller et venir entre la schématisation et le matériau (ce type de navigation est proposée par d'autres logiciels d'analyse de textes, comme *NVivo*, par exemple). 
 * L'éditeur pourrait assister l'agrégation des schématisations de codage axial (les doubles bâtonnets et les doubles triangles, illustrés pages 104, 108 et 109 du *Manuel*) en une schématisation de codage sélectif (illustrée page 118 du *Manuel*), selon les conventions explicitées pages 116-117  du *Manuel*. Agréger des diagrammes serait précieux pour l'analyste et offrirait également des possibilités de navigation supplémentaires : cliquer sur un lien de la schématisation finale permettrait de "remonter" au diagramme de codage axial d'où cette articulation provient. Les *ancrages* de la schématisation finale (s'appuyant sur des schématisations de codage axial) seraient ainsi, eux aussi, gérés par le système. 
 * Ce qui précède n'implique pas nécessairement de disposer d'une interface WYSIWYG : une image dotée de liens dynamiques pourrait aussi être générée à partir de la déclaration des noms de nœuds et de leurs relations. 

* La **table des propriétés** (présentée dans le *Manuel d'analyse qualitative*, pages 99-101) nécessite un mode de saisie spécifique. 
 * Les noms de lignes de ce tableau devraient pouvoir être saisis librement. 
 * Les entêtes de colonnes seraient choisis parmi les étiquettes créées (propriétés, dimensions, catégories). 
 * Les cellules du tableau devraient comporter la référence (peut-être via un hyperlien) à un passage d'un compte-rendu de terrain.

N'hésitez pas à me relancer si quelque chose n'était pas clair. Peut-être les schématisations et la table des propriétés méritent-elles qu'on leur dédie chacune une *issue*. Je suis bien conscient qu'elles nécessitent plus de travail que la "simple" saisie de texte. Elles jouent néanmoins un rôle important dans le travail de conceptualisation en recherche qualitative.

Le projet avance bien. Merci de vos contributions et bon courage pour la suite !

**Comment by ConstantSIDJUI** [comment]
Test de recette pour la création d'un compte rendu opérationnel à partir d'un compte rendu théorique.

1- vérifier que le background (tout ce qui c'est fait avant) du compte rendu opérationnel à été bien réaliser si non on doit au préalable:

- Créer un Projet;
- créer un compte rendu de terrain;
- faire un étiquetage;
- créer un compte rendu de codage;
- créer un compte rendu théorique;

2- étape de création du compte rendu opérationnel
- sur la page du compte rendu théorique, cliquer sur le type: compte rendu opérationnel;
- vérifiez que le compte rendu de coda n'est plus visible;
- vérifier que le compte rendu opérationnel est visible;
- renseigner les différent champs (Auteur, Type, etc)
- cliquer sur enregistrer.

**Comment by salamata** [comment]
Test de recette pour la création d'un compte rendu opérationnel à partir d'un compte rendu théorique avec RSpec syntax :

require 'spec_helper'
feature 'Créer un memo' do
scenario 'for a published article' do
visit '/'
click_on 'Compte rendu théorique'
click_on 'Créer compte rendu opérationnel'
fill_in 'Auteurs', :with => 'christophe-lejeune'
fill_in 'Titre', :with => 'compte rendu opérationnel'
fill_in 'Type', :with => 'compte rendu opérationnel'
fill_in 'Date', :with => '05/05/2015'
fill_in 'ancrage', :with => 'Compte rendu théorique'
fill_in 'URL', :with => 'https://github.com/Hypertopic/Cassandre/issues'
fill_in 'Memo', :with => 'L'analyse consigne les pistes à suivre dans des comptes-rendus opérationnels. Cela peut impliquer des passages en bibliothèque, orienter la suite du terrain ou suggérer des pistes de conceptualisation à venir.
Dans l'exemple de la construction de maison, les propriétés articulées (à savoir, le "difficultés impréus" et "se motiver" méritant un approfondissement.
-Se motiver est un processus doté d'une historicité propre: les conditions pour amorcer ce processus différent de celles contribuant à le poursuivre ou à l'arreter. Ces différentes conditions méritent d'être explorées.
-Le rôle que jouent les imprévus dans ce processus dépend de leur nature, de leur nombre, de leur répétition et de leur sévérité. Par ailleurs, les imprévu ne sont évidemment pas seuls à intervenir dans le processus. '
click_on 'Enregistrer'
visit '/'
expect(page).to have_content 'compte rendu opérationnel'
end
end

**Comment by christophe-lejeune** [comment]
Waow. Les choses se concrétisent. 

Quelques remarques : 
* Pour être consistante, l'interface ne devrait pas passer de "mémo" à "compte-rendu". Je préconise d'utiliser "compte-rendu" du début à la fin. 
* Le titre devrait toujours différer du type. Le titre d'un compte-rendu opérationnel pourrait être "Échantillonnage des dimensions de se motiver"
* Dans la mesure où l'utilisateur clique sur un bouton mentionnant le type de compte-rendu, il ne me semble pas utile de lui demander de préciser le type (le système comme l'utilisateur savent de quel type il s'agit)
* De la même manière, dans la mesure où l'utilisateur est identifié, il ne me semble pas non plus utile de lui demander de déclarer qui il est (le système le sait déjà).
* Enfin, c'est sans doute du détail, mais le contenu proposé ici ne correspond pas vraiment à celui d'un compte-rendu opérationnel. 

Voilà, je peux évidemment me tromper. N'hésitez pas à me le signaler le cas échéant.

**Comment by supertinou** [comment]
*Note :* @salamata, tu peux utiliser le formatage Markdown sous forme de code : https://help.github.com/articles/markdown-basics/#code-formatting  afin améliorer la visibilitée du test de recette.

**Comment by ConstantSIDJUI** [comment]
@supertinou est-il nécéssaire d'utiliser le formatage Markdown?

**Comment by PabloPrudhommeau** [comment]
Je pense que le markdown est crucial à la lisibilité des différentes informations diffusées dans chacunes des issues. Il est d'autant plus important de favoriser le markdown pour discerner le code (ou test de recette) du texte. @supertinou a raison de souligner ce point.

**Comment by christophe-lejeune** [comment]
J'invite @ConstantSIDJUI et @salamata à corriger la lisibilité de leur test de recette.

**Comment by salamata** [comment]
J'ai eu un petit soucis lors de la modification du test de recette "rediger un mémo" avec l'URL. J'ai pas un lien juste une chaine de caractère.

**Comment by ltosi** [comment]
@ConstantSIDJUI et @salamata : je pensais que vous l'aviez commencé pendant le TD?

**Comment by salamata** [comment]
Pourquoi la question?

**Comment by valentinlefevre** [comment]
Suite à la correction de la lisibilité du test de recette de @salamata peut-on concidérer la fonctionnalité comme "recettée"?

**Comment by christophe-lejeune** [comment]
Je ne sais pas ce qu’est une fonctionnalité « recettée ». Bien que je ne sois pas sûr que ce soit à moi de répondre à cette question, j’accepte que vous m’expliquiez de quoi il retourne et essayerai, à mon tour, de répondre à votre question.

**Comment by valentinlefevre** [comment]
La façon la plus simple de présenter les choses seraient de vous demander si, concernant la fonctionnalité abordée dans cette issue, l'analyse fonctionnelle qui a été menée vous satisfait ou si vous envisagez encore de nouveaux points la concernant? 

Cela nous permettra d'actualiser la liste des priorités et de nous concentrer sur les autres fonctionnalités et participer au développement pour les plus courageux d'entre nous.

**Comment by benel** [comment]
@valentinlefevre À moins de prendre le temps de "raconter" le test de recette à votre client, vous ne pouvez pas lui demander comme cela de valider le scénario correspondant.
Par ailleurs, il faut au préalable vérifier que le test de recette est cohérent avec la maquette et avec le scénario. Comme ce n'est pas le cas, il faudra corriger (au moins) l'un des trois.

**Comment by christophe-lejeune** [comment]
Il me semble, comme vous le suggérez, que nous avons fait le tour de cette fonctionnalité. 

Voici néanmoins quelques points de détails sur la congruence entre le test de recette et la maquette : 
* Dans la mesure où l'utilisateur clique sur un bouton mentionnant le type de compte-rendu, il ne me semble pas utile de lui demander de préciser le type (le système comme l'utilisateur savent de quel type il s'agit). 
* Dans le test de recette, l'utilisateur clique sur un "compte-rendu théorique" avant de créer un compte-rendu opérationnel. Ce qui apparaît à la racine ne devrait-il pas être le nom d'un compte-rendu théorique, et non son type ? 
* Le choix des ancrages n'implique-t-il pas de choisir, dans une liste, le nom d'un compte-rendu existant (et non seulement son type) ? 
* A quoi correspond l'URL qui est mentionnée dans le test de recette, et non dans la maquette ? 
* Le bouton "Enregistrer" n'apparaît pas sur la maquette.

**Comment by valentinlefevre** [comment]
Effectivement j'aurais du relire le test de recette avec la maquette en parallèle, je me serais rendu compte des problèmes que vous abordez. Ce sera corrigé pour vendredi.

**Comment by valentinlefevre** [comment]
Voilà la nouvelle version de la maquette et le test de recette qui lui est associée. Cette maquette et ce test se basent sur le fait que dans la page permettant la visualisation du journal de bord, l'utilisateur clique sur un bouton " ajouter une entrée au journal de bord" (par exemple).

Maquette
![image](https://cloud.githubusercontent.com/assets/6525895/7837028/ef86d184-0484-11e5-9e6b-96b9a9166ad9.png)
La date sera ajoutée automatiquement, l'auteur aussi en récupérant le nom/prénom de l'utilisateur qui rédige l'entrée du journal de bord en question.
![image](https://cloud.githubusercontent.com/assets/6525895/7837564/25714aba-0488-11e5-8c30-256dd81b9769.png)



Test de recette

``` ruby
require 'spec_helper'
feature 'Créer un compte rendu' do
scenario 'rédiger un compte rendu analytique' do
visit '/'
fill_in 'Titre', :with => 'Marcher/Ne pas marcher'
click_on 'ajouter des ancrages'
click_on 'analyse théorique'
fill_in 'Memo', :with => 'L''analyse consigne les pistes à suivre dans des comptes-rendus opérationnels. Cela peut impliquer des passages en bibliothèque, orienter la suite du terrain ou suggérer des pistes de conceptualisation à venir.
Dans l''exemple de la construction de maison, les propriétés articulées (à savoir, les "difficultés imprévus" et "se motiver" méritant un approfondissement.
-Se motiver est un processus doté d''une historicité propre: les conditions pour amorcer ce processus différent de celles contribuant à le poursuivre ou à l''arreter. Ces différentes conditions méritent d''être explorées.
-Le rôle que jouent les imprévus dans ce processus dépend de leur nature, de leur nombre, de leur répétition et de leur sévérité. Par ailleurs, les imprévu ne sont évidemment pas seuls à intervenir dans le processus. '
click_on 'Enregistrer'
click_on 'un Compte-rendu analytique'
visit '/'
expect(page).to have_content 'Compte rendu analytique : Marcher/Ne pas marcher'
end
end

Est ce que cela vous semble plus cohérent ?

**Comment by christophe-lejeune** [comment]
Je me permets quelques remarques additionnelles sur la dernière correction de la maquette. 

* Les interfaces figurant sur les maquettes sont francophones. «Name of the project» gagnerait donc à être remplacé par «Journal de bord», comme vous l'avez fait sur l'autre maquette, ci-dessus. 
* Le scénario d'utilisation prévoit clairement que l'utilisateur choisisse le type de compte-rendu avant d'ouvrir la fenêtre d'édition. Il n'est donc pas nécessaire que le bouton d'enregistrement précise ce type. En fait, ceci nous indique qu'il subsiste une confusion entre le statut des différentes fenêtres et l'ordre de leur succession. 
    * Si les fenêtres de consultation et d'édition sont les mêmes, nous avons besoin de deux boutons différents, l'un permettant d'enregistrer le compte-rendu courant et l'autre de créer le compte-rendu suivant. 
    * Si les fenêtres de consultation et d'édition sont distinctes, le bouton d'enregistrement n'est nécessaire qu'en édition. Celui permettant de créer le compte-rendu suivant qu'en consultation.   

Je préconise que nous éclaircissions ces points avant d'évaluer la cohérence de la maquette, du scénario et du test de recette. 

Dernière remarque : il est un peu déstabilisant que les modifications que vous apportez à la maquette se répercutent sur ses versions précédentes (plus haut dans ce ticket). Cela risque bien de rendre le fil de ce ticket difficile à appréhender par la suite.

**Comment by valentinlefevre** [comment]
@christophe-lejeune concernant les différents points abordés :
- Il est vrai que le projet dans son ensemble aurait besoin d'un gros travail d'uniformisation et gagnerait à être plus homogène, que ce soit concernant l'esthétique, le vocabulaire utilisé ou le positionnement des différentes éléments envisagés, nous aborderons ce point en groupe lors du tp.
- Il subsiste effectivement une confusion concernant le second point abordé, si vous vous référez à la maquette datant du 20 avril mise en ligne par @EdwardNjango il est déjà question d'une organisation semblable à la maquette soumise il y a 2 jours, il y a donc un point à éclaircir concernant l'organisation des fenêtres et afin d'avoir une meilleure vision de tout cela nous allons aborder ce point en groupe durant le tp.
- Et concernant les modifications j'aurais du savoir que github ne récupérait pas une image mais le lien vers l'image représentant l'état du mockup en question et que toute modification du mockup entraîne une modification des images de ce mockup. Je veillerai à ne pas reproduire cela à l'avenir.

Nous vous ferons un point concernant les 2 premiers éléments abordés à la suite de notre réunion.

**Comment by valentinlefevre** [comment]
@christophe-lejeune un gros travail homogénéisation a été réalisé pendant le séance de ce vendredi, nous ouvrirons prochainement une issue relative à cela, elle devrait répondre à un certain nombre de problématiques posées concernant la cohérence entre les différentes fonctionnalités du projet.

**Comment by ltosi** [comment]
> Si les fenêtres de consultation et d'édition sont les mêmes, nous avons besoin de deux boutons différents, l'un permettant d'enregistrer le compte-rendu courant et l'autre de créer le compte-rendu suivant.
Si les fenêtres de consultation et d'édition sont distinctes, le bouton d'enregistrement n'est nécessaire qu'en édition. Celui permettant de créer le compte-rendu suivant qu'en consultation.

Je reprends ces remarques : l'utilisateur a besoin de contexte, et un bouton d'enregistrement ne doit pas nécessiter de choix de la part de l'utilisateur, sous peine de perdre des données.

**Comment by valentinlefevre** [comment]
@ltosi oui le travail effectué avec @Slaals intègre ces remarques

**Comment by christophe-lejeune** [comment]
Pourriez-vous publier dans ce ticket les maquettes mises à jour montrant : 
1. La fenêtre de consultation d'un compte-rendu, à partir de laquelle on peut créer un nouveau compte-rendu
2. La fenêtre de modification comportant le bouton "Enregistrer" du compte-rendu courant.

**Comment by valentinlefevre** [comment]
### Consulter un compte-rendu 

![image](https://cloud.githubusercontent.com/assets/6525895/8037220/db6e58e4-0dfc-11e5-9c1d-01227412eb89.png)


### Rédaction d'un compte-rendu

![image](https://cloud.githubusercontent.com/assets/6525895/8037261/0ad17760-0dfd-11e5-8228-d2e6d81d88cd.png)

Les maquettes ci-dessus viennent du ticket d'unification, cela fait un peu doublon non?

**Comment by christophe-lejeune** [comment]
L'idée n'est évidemment pas de dédoubler la discussion mais d'éventuellement la reprendre ici pour ne pas surcharger le ticket d'unification (#56).

**Comment by christophe-lejeune** [comment]
Lors de notre dernière réunion, nous avons parlé d'ajouter à la fenêtre de rédaction d'un compte-rendu **de terrain** la possibilité de joindre des photographies. Prendre des photos des lieux fait en effet partie des usages de terrain en recherche qualitative.

**Comment by Slaals** [comment]
:+1: Je pense que c'est nécessaire de discuter sur les fonctionnalités une à une via les tickets qui les correspond. La ticket unification ( #56 ) servira juste à centraliser les retouches et ajustements, ainsi que décrire les scenarii.

**Comment by christophe-lejeune** [comment]
Dans le cas particulier du compte-rendu de terrain, il faut également prévoir le cas des transcriptions d'entretiens, qui sont structurées en tours de parole (comme c'est le cas actuellement dans Cassandre).

**Comment by valentinlefevre** [comment]
>Vous faites bien de le rappeler ! Une proposition sera certainement faite d'ici vendredi !

Concernant les photographies peut-on envisager qu'elles soient intégrer au texte du compte-rendu via un simple copier-coller ou glisser-déposer?

>Dans le cas particulier du compte-rendu de terrain, il faut également prévoir le cas des transcriptions d'entretiens, qui sont structurées en tours de parole (comme c'est le cas actuellement dans Cassandre).

Effectivement les maquettes ne présentent pas une configuration permettant la saisie d'un échange, peut-on se baser sur ce qui est pour l'instant proposé par Cassandre ?

**Comment by christophe-lejeune** [comment]
>Concernant les photographies peut-on envisager qu'elles soient intégrer au texte du compte-rendu via un simple copier-coller ou glisser-déposer?

Plus c'est simple, mieux c'est. Un glisser-déposer serait parfait. 

>Effectivement les maquettes ne présentent pas une configuration permettant la saisie d'un échange, peut-on se baser sur ce qui est pour l'instant proposé par Cassandre ?

Bien entendu. Le système actuel est cependant perfectible, comme me l'ont fait récemment remarquer mes étudiants : 
* Actuellement, vu que l'ajout d'un tour de parole rafraîchit la page, l'utilisateur se retrouve en haut de page alors qu'il est en train de transcrire (en bas de page). C'est particulièrement gênant.
* Les croix de suppression d'un tour de parole étant d'effet immédiat, il n'y a pas de possibilité de retour en arrière. Certains étudiants ont témoigné avoir dû relire l'ensemble de leur entretien après avoir cliqué par erreur sur une de ces croix.

**Comment by valentinlefevre** [comment]
>Ces deux derniers commentaires concernent cependant peut-être moins la maquette que le comportement du formulaire.

Effectivement mais mieux vaut poser les choses maintenant : 
- Ajout dynamique des éléments sans rafraîchissement de page,
- Ajout d'une étape de validation dans le processus de suppression d'un ou plusieurs tours de parole.

**Comment by AndreMarvell** [comment]
@christophe-lejeune conformément à votre retour sur le commentaire d'un membre collaborateur, voici une proposition de maquette gérant ce cas :

![commentaire cr par un collaborateur 2](https://cloud.githubusercontent.com/assets/5513545/8163297/8be70056-1382-11e5-80d1-59cafa8dee14.png)

Comme on peut le voir, le collaborateur connecté, *Olivier Ménard*, peut créer un compte-rendu s'appuyant sur le compte-rendu consulté en cliquant sur le bouton dédié.

**Comment by AndreMarvell** [comment]
Conformément aux évolutions des maquettes dans l'issue #56, voici la nouvelle maquette : 

![commentaire cr par un collaborateur 3](https://cloud.githubusercontent.com/assets/5513545/8244430/db169a42-1620-11e5-8644-c3335115a9f4.png)
