### ISSUE TITLE
Commenter un compte-rendu

### ISSUE THREAD

**Issue by Yeahger** [Hypertopic/Cassandre#45]
# Summary of required features and fixes
- [x] Memos can be commented
- [x] The id of the person that authored of the comment is saved
- [x] Comment may include quotes from the memo
- [x] The author of the memo may define who is allowed to comment his/her memo
# Discussion

Issue créee avec @AndreMarvell.

Un utilisateur peut laisser un commentaire sur un mémo, s'il possède un compte.
Voici des idées de ce que pourrait comporter un commentaire : 
- l'auteur
- la date
- le message
- citer un extrait du mémo
- joindre un document
- faire référence à un autre mémo
- noter la pertinence du commentaire (système de + / - )

Concernant la disposition des commentaires et de leurs réponses, nous avons songé à deux possibilités : 
- une hiérarchisation des commentaires : ce système est assez visuel, mais est plus compliqué à mettre en place. Il est plus pertinent lorsqu'il y a des possibilités d'avoir des grosses discussions sur un sujet.
- une réponse directe envers une personne en citant son pseudonyme avec "@" : plus simple à mettre en place, peut être suffisant pour notre cas.

Ci-dessous, une illustration des deux cas :
![capture d ecran 2015-04-10 a 11 37 16](https://cloud.githubusercontent.com/assets/3393357/7085330/00ecccfa-df76-11e4-91a9-e9f3624131e9.png)

**Comment by christophe-lejeune** [comment]
You assume that everyone owns an account on the platform. However it is certainly not the case when I share a memo with a customer, a lay person or an actors. It could thus be useful to clarify the way memos are shared with such a person (in #41) prior to decide how commenting rights are managed.

**Comment by Yeahger** [comment]
On peut envisager deux possibilités : 
- un utilisateur doit avoir un compte pour commenter un mémo : dans ce cas, il faut que l'inscription soit rapide et simple. L'avantage est qu'il sera facile de retrouver l'identité des personnes qui commentent, et de garantir le caractère privé des mémos, qui ne seront "commentables" que pour ces personnes.
- un utilisateur peut commenter sans avoir de compte : pas besoin d'inscription, donc plus rapide. Cependant, l'utilisateur devra renseigner manuellement son identité, et n'importe qui peut se faire passer pour une autre personne.

**Comment by Yeahger** [comment]
Voici une première ébauche de la maquette à poursuivre sur le balsamiq de l'UTT.
![capture d ecran 2015-04-10 a 12 59 17](https://cloud.githubusercontent.com/assets/3393357/7086446/6dc5bffc-df81-11e4-8ccf-558b37e245fa.png)

**Comment by mchidaine** [comment]
Avec @EdwardNjango nous avons rendu les trois dernières fonctionnalités plus explicites, avec la possibilité de compter le nombre de like/dislike du commentaire. 

Concernant l'accès aux commentaires, il nous semble plus simple que seuls les utilisateurs ayant un compte puissent commenter. Cela simplifiera les réponses directes et on aura plus de contrôle. 
Il faudra donc mettre en place une inscription simplifiée, comme dit précédemment, avec juste Nom/Prénom/Adresse email par exemple. 

![commenter memo](https://cloud.githubusercontent.com/assets/4137917/7118673/1df8e2ce-e201-11e4-993e-d884e9ed2671.png)

**Comment by mchidaine** [comment]
On se pose la question du caractère privé des commentaires : 
Si on partage un mémo à quelqu'un qui n'a pas de compte, est-ce qu'il pourra voir les commentaires des autres (même sans pouvoir commenter) ou est-ce qu'il devra créer un compte pour commenter ET voir les commentaires?

Au niveau des types de compte-rendus, on considère qu'on peut commenter tout ce qu'on peut partager, c'est à dire tous les mémos.

**Comment by AndreMarvell** [comment]
@mchidaine : @Yeahger et moi pensons que "la possibilité de compter le nombre de like/dislike du commentaire" est une fonctionnalité plus orientée réseaux sociaux et donc pas très utile dans le cas d'un mémo. Le nombre de personnes ayant accès à un mémo est assez restreint et leur but n'est pas d'aimer un commentaire ou pas. Cela est bien sur aussi valable pour la fonctionnalité que nous avions faite (système + et -).
Cette fonctionnalité ne nous semble donc plus très pertinente pour Cassandre.

**Comment by AndreMarvell** [comment]
Cependant concernant l'inscription obligatoire, après reflexion, nous pensons que c'est trop contraignant pour l'utilisateur (notamment les professionnels interviewés) car c'est souvent gênant de créer un nouveau compte sur internet.

Du coup nous suggérons la possibilité de pouvoir commenter : 
- En tant qu'invité : l'utilisateur aura à préciser le nom et le prénom uniquement
- En étant connecté : l'utilisateur possède un profil sur Cassandre et pourra s'y connecter pour commenter
- En s'inscrivant : l'utilisateur pourra choisir de créer un compte en un clic (nom, prénom, mot de passe,email)

Ce qui est bien illustré par la maquette ci-dessous :

![commenter memo anonyme](https://cloud.githubusercontent.com/assets/5513545/7200612/021374ec-e4ff-11e4-8697-e87f2b89e2be.png)


PS: Pour répondre à @mchidaine au sujet du caractère privé des commentaires, nous pensons cela est lié au caractère privé du mémo concerné. Si l'utilisateur a reçu le lien de partage du mémo, il pourra voir le commentaire et commenter (tout en suivant les trois cas évoqués précédemment), dans le cas contraire il ne verra ni le mémo ni les commentaires.

**Comment by christophe-lejeune** [comment]
* Lorsqu'un utilisateur possédant un identifiant "commente" d'un compte-rendu, on se trouve dans la situation "classique" d'un compte-rendu s'appuyant sur un autre compte-rendu (*Grounding*). Dans ce cas de figure, il n'y a pas lieu de prévoir de nouvelle fonctionnalité : la création d'un compte rendu est gêrée par ailleurs (#40).
* L'idée utilisée dans la maquette (de représenter, au moyen d'indentations, le fil des comptes-rendus successifs, comme le font les forums de discussions ou les réseaux sociaux) peut pourrait être utile à la cartographie du journal de bord (#47). 
* La fonctionnalité de *feedback* (dont nous discutons sur la présente page) s'impose donc essentiellement lorsqu'une personne est **invitée** à consulter un compte-rendu particulier. Cet invité devrait pouvoir rédiger son feedback sans être authentifié, comme le propose @AndreMarvell. 
* Je ne suis pas sûr qu'il faille prévoir d'autres statuts ni distinguer entre un utilisateur "connecté" et "identifié" (je ne vois moi-même pas la différence).
* L'accès aux feedbacks (commentaires) devraient être liés aux "droits" du compte-rendu. Seuls les **auteurs** du compte-rendu commenté devraient y avoir accès. En particulier, il n'y a pas de raison qu'un invité ait accès aux autres feedbacks.  
* @mchidaine , @AndreMarvell et @Yeahger ont raison : compter n'est pas pertinent ici (puisqu'on *analyse sans compter ni classer*).

**Comment by ChangruLU** [comment]
Test de recette pour commenter un memo avec RSpec syntax :

``` ruby
require 'memo'
feature 'Commenter un memo' do
scenario 'Commenter en tant qu\'un invité' do

visit '/'
fill_in 'Nom', :with => 'LU'
fill_in 'Prénom', :with => 'Changru'
fill_in 'Commentaires', :with => 'Coucou\, le memo est ...'
click_on 'Envoyer'
visit '/'
expect(page).to have_content 'Memo commenté'
end

scenario 'Commenter en tant qu\'un inscrit' do

visit '/'
fill_in 'Commentaires', :with => 'Coucou\, le memo est ...'
click_on 'Envoyer'
visit '/'
expect(page).to have_content 'Memo commenté'
end
end

Rédigé avec @valentinlefevre

**Comment by ConstantSIDJUI** [comment]
@ChangruLU Il manque quelques points sur le test de recette afin qu'il soit cohérent avec la dernière maquette présentée:
- on doit pouvoir référencer un mémo
- citer un extrait du mémo
- joindre un document

Par ailleurs la question que je me pose est de savoir si un invité aura la possibilité de réaliser ses dernières actions aussi bien qu'in inscrit?

**Comment by christophe-lejeune** [comment]
Un commentaire se rapportant toujours au compte-rendu commenté, je ne suis pas convaincu que les fonctions évoquées par @ConstantSIDJUI soient utiles. 

Dans un premier temps, je suggère donc que la maquette du 17 avril soit simplifiée (en tenant compte de mes commentaires du 19 avril). C'est l'occasion de l'homogénéiser avec celles proposées dans les autres tickets.

Nous évaluerons ensuite la consistance entre la maquette mise à jour et le test de recette.

**Comment by AndreMarvell** [comment]
Conformément à ce qui a été évoqué au cours de la réunion d'hier, nous avons  modifié la maquette de commentaire d'un compte rendu, sous forme de deux maquettes pour différencier les cas de commentaires : 
- Commentaire d'un collaborateur (déjà identifié)
- Commentaire d'un invité

#### Commentaire d'un collaborateur

![commenter memo](https://cloud.githubusercontent.com/assets/5513545/8004097/0f3e6fce-0b7d-11e5-92d7-9c8459d7bcee.png)

Dans la maquette ci-dessus, l'utilisateur est déjà connecté. Le formulaire de commentaire affiche ainsi sa photo de profil et son nom, et l'utilisateur n'a plus qu'à saisir son commentaire.
Nous avons choisi d'illustrer dans cette maquette, une référence à un autre utilisateur par son pseudonyme grâce au caractère *@*.


#### Commentaire d'un invité

![commenter memo anonyme](https://cloud.githubusercontent.com/assets/5513545/8004112/1daac512-0b7d-11e5-85e1-a081e1c9c3e6.png)

Dans cette maquette, l'utilisateur est invité et ne dispose pas de compte, il doit donc saisir son nom ou pseudonyme ainsi que le commentaire qu'il souhaite ajouter.
Comme on peut le remarquer, nous avons choisi d'illustrer à travers cette maquette, l'une des principales fonctionnalités du commentaire de compte rendu : *l'ajout d'une citation du compte rendu consulté*. Ce qui est clairement expliqué dans le test de recette qui suivra.

Maquettes réalisées avec @Yeahger

**Comment by Yeahger** [comment]
##### Tests de recette sur les maquettes mises à jour par @AndreMarvell :

###### Commenter en étant connecté, avec référence à un utilisateur (maquette n°1)
``` ruby
require 'compte-rendu'
feature 'Commenter un compte-rendu' do
scenario 'Commenter en étant connecté, avec référence à un utilisateur' do

visit '/'
fill_in 'Commentaire', :with => '@A'
click_on 'André Marvell'
fill_in 'Commentaire', :with => 'Les jeunes, il faut les décider à travailler. Mais il y a 
travailler manuellement et il y a travailler durement ! Parce que le métier de boulanger est 
un métier très dur !'
click_on 'Envoyer'
visit '/'
expect(page).to have_content 'Compte-rendu commenté'
end
```

###### Commenter en étant invité, avec une citation (maquette n°2)
``` ruby
require 'compte-rendu' 
feature 'Commenter un compte-rendu' do
scenario 'Commenter en étant invité, avec une citation' do

visit '/'
fill_in 'Nom', :with => 'Olivier Ménard'
click_on 'Citer'
paste_in 'Citation', :with => 'Voilà comment on fonctionne et puis par une fois par semaine, on 
fait une réunion qui permet de savoir ce qu’on doit avoir, tout ce qu’on a fait et d’une 
organisation … Voilà. '
click_on 'Ok'
fill_in 'Commentaire', :with => 'Les jeunes, il faut les décider à travailler. Mais il y a 
travailler manuellement et il y a travailler durement ! Parce que le métier de boulanger est un
 métier très dur !'
click_on 'Envoyer'
visit '/'
expect(page).to have_content 'Compte-rendu commenté'
end
```

**Comment by christophe-lejeune** [comment]
Merci pour les révisions proposées. Il est cependant un peu dommage d'avoir conçu une nouvelle maquette ne tenant pas compte des échanges nourris que nous avons eus. 

* Compte-tenu que le commentateur n'a sans doute aucune idée du statut de son commentaire, le bouton « Enregistrer » ne devrait pas comporter de choix multiples (nous avions d'ailleurs exclu cette option de tous les boutons du même type). 

* Comme mentionné le 19 avril (ci-dessus) et répété hier, la contribution d'un membre de l'équipe correspond à la rédaction d'un compte-rendu. En bonne logique, le maquettage de ce cas de figure doit donc correspondre à ce que nous avons convenu dans le ticket #40, à ceci près qu'un seul ancrage doit apparaître (le compte-rendu commenté). Si vous souhaitez ajouter des fonctionnalités à ce cas de figure, il devrait logiquement être suggéré (et discuté) dans le ticket #40. 

* Nous avons convenu ci-dessus que les commentaires ne sont pas visibles par les commentateurs. Or, sur la maquette proposée représente la saisie d'un commentaire, au côté d'autres commentaires (visibles). C'est donc inconsistant. 

* Vous m'avez convaincu de l'opportunité d'offrir une option de citation du compte-rendu commenté. Le copier-coller proposé ne me semble pas très ergonomique. Il devrait y avoir moyen de proposer au commentateur de sélectionner le passage qu'il commente.  

Avant d'évaluer les tests de recette, je vous propose donc de corriger les maquettes en tenant compte des commentaires ci-dessus et de la discussion qui les précède. Les maquettes nécessaires devraient comprendre : 
* Le cas "classique" du participant rédigeant un compte-rendu adossé à un autre. 
* Le cas de l'invité commentant un compte-rendu.  
* La fonctionnalité de citation (éventuellement intégrée à la maquette précédente).  
* Le parcours, par l'auteur du compte-rendu original, des différents comptes-rendus le commentant (les deux types devant être clairement distingués). 

Bon travail et à bientôt

**Comment by AndreMarvell** [comment]
@christophe-lejeune Merci pour votre retour.
Désolé pour les erreurs commises par rapport aux nouvelles maquettes proposées, il s'agit surtout d'une incompréhension de ma part, notamment sur le cas du commentaire d'un collaborateur.

Je vais donc reprendre point par point, les remarques que vous m'avez faites.

- Concernant le bouton « Enregistrer », de quel bouton parlez-vous exactement, car je ne vois aucun bouton Enregistrer sur les maquettes ? Si seulement vous parlez du choix multiple suivant :

![capture d ecran 2015-06-07 a 21 36 50](https://cloud.githubusercontent.com/assets/5513545/8025821/8230b1b2-0d63-11e5-9c1a-b20988eeeedc.png)

Il s'agissait d'une manière pour un collaborateur de référencer un autre membre, d'ou les trois choix auto-complétés à partir de A. Mais comme vous l'avez re-précisé, ce cas de figure correspond à la rédaction d'un autre compte rendu.

- Concernant la contribution d'un membre de l'équipe, comme je l'ai évoqué plus haut, il s'agissait d'une incompréhension, ce cas de figure n'a donc pas besoin d'être pris en compte ici. Lorsqu'un collaborateur consultera un compte-rendu, un bouton lui proposera de rédiger un compte-rendu à partir du CR consulté, qui sera automatiquement ancré au nouveau CR

###### Commentaire d'un membre collaborateur
![commentaire cr par un collaborateur](https://cloud.githubusercontent.com/assets/5513545/8025910/f4dca78c-0d65-11e5-8dac-af8b491dc847.png)


- Concernant la visibilité des commentaires par les commentateurs, seule l'auteur du compte-rendu original pourra voir tous les commentaires de l'ensemble des invités. L'invité ne verra que son commentaire ainsi que les réponses apportées par l'auteur du compte-rendu original.

NB: Toutes les réponses se feront par l'intermediaire de commentaires indentés par rapport au premier comme on peut le voir dans la maquette ci-dessus.


###### Commentaire d'un membre invité
Cette maquette représente le commentaire d'un CR par un invité ayant déjà commenté le CR mais s'apprêtant à répondre à la réponse apporté par l'auteur du CR à son premier commentaire. On part du principe que le système reconnait un invité par son lien d'invitation, et peut donc se rappeler de l'ensemble de ses commentaires. Comme on vous pourrez le voir, j'ai aussi illustrer l'affichage d'une citation dans un commentaire

![commenter memo anonyme](https://cloud.githubusercontent.com/assets/5513545/8026070/dbe69064-0d68-11e5-8f4b-00715e56b5ab.png)


- Concernant la fonctionnalité de citation du compte-rendu commenté, voici une proposion de maquette

###### Citation d'une partie du compte-rendu
Dans la nouvelle maquette, l'utilisateur pourra sélectionner une portion du compte rendu et un clic droit, lui permettra d'afficher les options de texte parmi lesquelles il pourra sélectionner "Citer". Le texte sélectionné sera automatiquement ajouté au champ de texte à l'intérieure des balises de citation "quote".


![commentaire cr par un invite citation](https://cloud.githubusercontent.com/assets/5513545/8026230/c9b2a3f0-0d6e-11e5-8bb5-3b94c3270281.png)



- Enfin  concernant le parcours de l'auteur du compte-rendu original, celui-ci verra tout d'abord les différents comptes-rendus le commentant, qu'il pourra consulter en cliquant dessus, et ensuite l'ensemble des commentaires des invités auxquels il pourra apporter des réponses. Et à moins que je me trompe, Il me semble que le ticket #56 illustre assez bien cette fonctionnalité. 


Avant de modifier les tests de recette, j'aimerai avoir votre avis sur les modifications apportées.

**Comment by christophe-lejeune** [comment]
Voici mes réactions à vos propositions : 
* Le commentaire sur le bouton «Enregistrer» n'est plus d'actualité.
* La fenêtre de rédaction d'un compte-rendu par un membre de l'équipe doit correspondre à la maquette proposée dans le ticket #40; ce n'est pas encore le cas. 
* Si vous souhaitez ajouter la fonctionnalité de citation d'un participant à la rédaction des comptes-rendus, je vous invite à la proposer dans le ticket approprié, à savoir #40
* Même remarque pour la proposition (pertinente) de renommage du bouton "Créer un compte-rendu s'appuyant sur celui-ci"
* Nous n'avons nul part évoqué la possibilité que les membres du projet réagissent aux commentaires des invités. De fait, ils ne le feront pas. Il n'est donc pas utile de prévoir d'indentation. 
* Vous proposez un menu contextuel, obtenu par clic droit, dont les items me semblent peu utiles : comment peut-on couper ou coller un texte sur lequel on a pas de droit d'édition ? Au final seul "citer" semble pertinent. 

  Je ne sais pas comment fonctionne la fonction "Citer" sur les forums. Voici néanmoins une proposition. Peut-être le menu contextuel est-il inutile et suffit-il de proposer que le bouton à droite du nom colle comme citation ce que l'utilisateur aura préalablement sélectionné. Un pop-up informatif devra lui expliquer la manœuvre s'il clique sur "Citer" sans avoir rien sélectionné.

**Comment by christophe-lejeune** [comment]
On pourrait également "intégrer" la citation et le commentaire en proposant une interface comparable à celle de l'étiquetage : l'invité pourrait consigner ses commentaires dans la marge, en regard du passage qu'il souhaite commenter. Je n'ai aucune idée des technologies à mobiliser mais, pour que cela fonctionne, il faut une interface ultra-intuitive. Les invités ne seront pas formés à utiliser la plateforme et risquent bien de la quitter à la moindre difficulté.

**Comment by AndreMarvell** [comment]
@christophe-lejeune Merci pour votre retour, et surtout désolé pour le temps de réponse assez long pour cette feature.

Conformément à votre retour, voici les améliorations faites : 

##### 1. Commentaire d'un membre collaborateur
Concernant le commentaire d'un collaborateur, une maquette sera proposé dans le ticket #40.

###### Maquette (Voir ticket #40 )


##### 2. Commentaire d'un invité
Concernant la fonctionnalité de citation, votre proposition d' intégration de la citation et du commentaire en proposant une interface comparable à celle de l'étiquetage, est certainement la plus intuitive et la plus ergonomique, mais compte tenu non seulement du temps restant et ressources pour mettre la mettre en place, nous avons majoritairement décidé de la proposer en amélioration éventuelle du système de commentaire.
Par rapport à cela, nous avons donc décidé de garder la précédente interface en prenant en compte votre dernier retour. Ainsi, pour effectuer une citation du compte-rendu commenté, l'invité devra selectionner le portion de texte et pourra ainsi la citer soit :
  - en effectuant un clic droit (qui n'affichera plus que l'option citer)
  - en cliquant sur l'option "Citer", à droite du nom, qui collera la portion de texte selectionné

###### Maquette

![commentaire cr par un invite 2 citation](https://cloud.githubusercontent.com/assets/5513545/8163170/e1c0001e-1381-11e5-9b06-ffa8da5504b8.png)



### Récap
Pour récapituler, dans le cadre d'un commentaire d'un compte-rendu, il n'y a qu'un seul cas possible, celui du commentaire d'un invité, étant donné que :
- Le rédacteur du compte-rendu original ne réagit pas aux commentaires des invités
- Le commentaire d'un collaborateur correspond à la rédaction d'un compte rendu s'appuyant sur celui consulté.

**Comment by AndreMarvell** [comment]
Conformément aux évolutions de l'issue #56, voici la nouvelle maquette : 

![commentaire cr par un invite 3 citation](https://cloud.githubusercontent.com/assets/5513545/8244457/3c4ee332-1621-11e5-8172-8e10eada4927.png)

Le commentateur invité n'étant pas authentifié et ayant des droits d'accès limité : 
- il n'aura pas accès à l'onglet des ancrages
- il n'aura pas accès à l'onglet des CR feuilles
- il n'aura pas besoin des boutons d'édition ou de partage disponibles dans l'entête du CR consulté

**Comment by christophe-lejeune** [comment]
I am unsure how comments should be stored in the database. 

1. An easy solution would be to store comments in the same (CouchDB) document than the memo itself. When a new comment is posted (or edited), the memo document is modified.
2. Another solution consists in storing each comments in a separate document. 
  * Showing comments then implies to gather all concerned documents. 
  * Adding or modifying a comment won't affect the memo document. 
3. An intermediate solution consists in storing the comments thread in a document, distinct from the memo. 
  * Showing all the comments requires to fetch only one document.
  * Commenting does not affect the memo document.

Not sure which solution is the more robust, efficient, RESTfull.

**Comment by benel** [comment]
- Number one is the simplest one,
- Number two minimizes conflict occurrences (when users are writing comments on the same memo at the same time),
- Number three has no real interest.

Note : You could also have solution "1bis" – Instead of displaying an memorizing the memo, waiting for user inputs and saving the new memo, you could display the memo, waiting for user inputs, getting again the memo and save it. Then you'll have something nearly as simple as number 1 but with the pros of number 2.

**Comment by benel** [comment]
> the pros of number 2

It's a bit less robust than number 2 (you'll have a conflict if users click the button on the very same 100ms) but far more robust than plain number 1 (in which you had a conflict whenever two users were on the same page as the same time for commenting).

**Comment by christophe-lejeune** [comment]
I am unsure how comments should be stored in the database. 

1. An easy solution would be to store comments in the same (CouchDB) document than the memo itself. When a new comment is posted (or edited), the memo document is modified.
2. Another solution consists in storing each comments in a separate document. 
  * Showing comments then implies to gather all concerned documents. 
  * Adding or modifying a comment won't affect the memo document. 
3. An intermediate solution consists in storing the comments thread in a document, distinct from the memo. 
  * Showing all the comments requires to fetch only one document.
  * Commenting does not affect the memo document.

Not sure which solution is the more robust, efficient, RESTfull.

**Comment by christophe-lejeune** [comment]
Thank you very much, Aurélien. This really makes sense. Here is thus the direction that my code is taking. 
* Memos can be commented. Of course, each comment has an author. Comments are saved in the memo document. 
* The source document is reloaded when the comment is saved, in order to avoid to overwrite other comments (or memo edits) submitted while the user was writing down his/her own comment.  
* Editing a memo follows the same principle : the original memo document (including the comments) is reloaded just before the memo is saved.

**Comment by benel** [comment]
As this issue is `done`, shouldn't it be closed?
