### ISSUE TITLE
Ajouter un ancrage à un compte-rendu

### ISSUE THREAD

**Issue by AndreMarvell** [Hypertopic/Cassandre#48]
# Summary of requested features
- [x] Add grounding to a memo.
  - [x] Needs refactoring.
- [ ] Remove one memo's grounding.
# Discussion

Tel qu'il a été minutieusement évoqué dans le ticket #40, la rédaction d'un compte rendu donné exige dans certains cas la prise en compte de plusieurs version de types de comptes rendus.

_Exemple_ : Le compte rendu théorique N°2 nécessite les comptes rendus de codage N° 1 et 2.

Dans ce cas, la solution idéale qui conviendrait au système de navigation retenu serait un système d'ancrage qui permettrait de référencer directement un compte rendu donné dynamiquement.

**Comment by sandrasongue** [comment]
Voici la maquette qui donne une idée de l'interface de l'affichage des ancrages d'un compte rendu donné.

![image](https://cloud.githubusercontent.com/assets/8090403/7336479/d3483888-ec00-11e4-912e-ec001bc97f4f.png)

**Comment by christophe-lejeune** [comment]
Je renomme le sujet de cette fonctionnalité en postulant que cette issue porte sur le fait que les comptes-rendus s'appuient sur d'autres comptes-rendus. N'hésitez pas à corriger cet intitulé si je me méprends.

**Comment by valentin-bonino** [comment]
![Maquette](https://utt.mybalsamiq.com/mockups/3079421.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

@mchidaine et moi avons réfléchis à une solution permettant l'ancrage multiple et nous avons pensé à un popup qui s'afficherait une fois le type du nouveau compte-rendu sélectionné.
Dans ce popup, on retrouve en premier lieu l'ancrage par défaut à partir duquel nous voulons réaliser le nouveau compte-rendu, puis dans une seconde partie on retrouve une liste de compte-rendus de même type à partir desquels on peut ancrer le nouveau compte-rendu (il reste à définir les types de compte-rendus que l'on veut retrouver dans cette liste).

**Comment by AndreMarvell** [comment]
@christophe-lejeune Je n'ai rien à rajouter par rapport au deux interventions.
@valentin-bonino la solution proposée me semble pertinente.

Pour la suite, face à quelques soucis au niveau ergonomique, nous avons modifié la maquette d'ajout des ancrages : 
- **Primo**, pour améliorer la compréhension de la maquette en donnant une plus grande importance au compte rendu rédigé, nous avons décidé de réduire la taille de la zone d'ancrage.
- **Secundo**, pour simplifier la lecture des ancres, les x premières lignes seront affichées par défaut, nous avons ajouté un bouton "**Lire la suite**" qui permettra de dérouler tout le contenu du compte rendu ancré.
- **Tercio**, nous avons décidé d'ajouter sur chacune des ancres, des chevrons, pour permettre aux utilisateurs de fermer ou ouvrir une ancre, en fonction de leurs besoins.

Ce qui donne le résultat suivant en image :

![image](https://cloud.githubusercontent.com/assets/5513545/7492133/e3dee636-f3f0-11e4-8a09-ab1a799f7dc8.png)

![image](https://cloud.githubusercontent.com/assets/5513545/7492242/19041484-f3f2-11e4-97b8-0d078865682b.png)


#### La maquette est donc prête à être évaluée.

**Comment by christophe-lejeune** [comment]
Je ne vois pas grand chose à redire. 

Juste une idée... Si l'on voulait simplifier les "aperçus" des ancrages, dans les **deux** dernières maquettes ci-dessus, on pourrait utiliser les astuces suivantes. 
* Ne pas afficher la ligne mentionnant l'auteur 
* Ne pas afficher la ligne mentionnant le type; le type pourrait être signalé par la couleur du cadre.
Ainsi, on gagne deux lignes à chaque ancrage.

**Comment by AndreMarvell** [comment]
@christophe-lejeune Je suis d'accord avec votre idée. Nous y avions même pensé, mais nous avons préféré garder la meme structure qu'un compte rendu classique pour ne pas dépayser l'utilisateur. Comme cela ne semble pas vous déranger voici les deux maquettes actualisées.

![image](https://cloud.githubusercontent.com/assets/5513545/7504955/781ba390-f44e-11e4-9a2c-04a3c1f16e4e.png)

**NB** : Comme on peut clairement le remarquer, en bas de page, pour occuper l'espace vide, nous avons décidé de placer une légende pour les couleurs de cadre des ancres, qui déterminent le type de codage. 

![image](https://cloud.githubusercontent.com/assets/5513545/7504949/6eaa505e-f44e-11e4-9753-f9bdceab993f.png)

**Comment by christophe-lejeune** [comment]
Bien ! 

Voici une série de suggestions, pour améliorer ces maquettes. 
* Par souci de cohérence, la même convention (couleur pour le type et omission de l'auteur) pourrait être utilisée pour le pop-up de la deuxième maquette. 
* Sur les deux maquettes, je vous invite à corriger "ajouter des ancres" en "ajouter des ancrages". 
* Dans la légende, ajoutez les traits d'union aux "comptes-rendus".
* Par souci de cohérence, "mémo sélectionné" gagnerait à devenir "compte-rendu sélectionné". 
* Il n'y a pas lieu d'intégrer le "compte-rendu analytique" à la légende, car un compte-rendu de scénario analytique constitue la conclusion finale d'une recherche. Il est donc peu vraisemblable qu'il soit mobilisé comme ancrage. Par contre, les "comptes-rendus théoriques" mériteraient de figurer dans cette légende. 
* Je préférerais que soit adoptés les couleurs et l'ordre suivant (cela correspondrait à ce que j'utilise dans mes enseignements)
  * Compte-rendu de terrain : noir 
  * Compte-rendu de codage : jaune 
  * Compte-rendu théorique : vert
  * Compte-rendu opérationnel : mauve 
* Si les deux maquettes sont censées illustrer un scénario d'utilisation, il faut choisir si le compte-rendu en cours d'édition est un compte-rendu théorique (1ère maquette) ou un compte-rendu de scénario analytique (2ème maquette).


Je me demande, par ailleurs, si la convention des couleurs ne pourrait pas être généralisée à l'ensemble des fenêtres. J'hésite cependant car je voudrais éviter que le journal de bord ressemble à un sapin de Noël. ;-)

**Comment by EdwardNjango** [comment]
Je me suis permis d'améliorer les maquettes faites par @AndreMarvell précédemment, le travail qui a été fait est le suivant : 
- Dans un premier temps les remarques de @christophe-lejeune ont été prises en compte
- Dans un deuxième temps, j'ai modifié  le visuel de la légende, en effet l'ancien visuel laissait penser à des boutons de navigation, par souci de clarté j'ai opté pour un visuel plus traditionnel.

Les maquettes sont présentées ci-dessous. 
![3028964](https://cloud.githubusercontent.com/assets/10283167/7571998/9bbf3f84-f81b-11e4-9754-3f4328759bfb.png)


![ancrages multiples2](https://utt.mybalsamiq.com/mockups/3088152.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

**Comment by Yeahger** [comment]
En alternative aux blocs colorés et à l'obligation d'afficher une légende des types de comptes-rendus, je propose l'utilisation d'icônes qui pourraient se trouver dans le coin supérieur gauche des blocs.
Voici un exemple (plagié honteusement sur Microsoft Office) pour illustrer mes propos :
![if05 - icons](https://cloud.githubusercontent.com/assets/3393357/7656056/56702e24-fb28-11e4-876b-5b75699027a5.png)

**Comment by christophe-lejeune** [comment]
Pourquoi pas, en effet, se doter d'icônes. 

Celles-ci devraient alors : 

* être aussi simples et lisibles que possible;
* éviter les "honteux plagiats";
* éviter de représenter un dossier. Le dossier fait penser au classement, et on évite de classer en recherche qualitative. 

Sans vouloir brider la créativité de @Yeahger, la proposition apparaissant dans le ticket #50, colorée comme dans le ticket #47, me semble rencontrer ces objectifs.

Quoi qu'il en soit, il importe de prévoir une cinquième couleur (le bleu) pour les trois comptes-rendus de scénario (Sc).

**Comment by ConstantSIDJUI** [comment]
@EdwardNjango pour une cohérence avec le ticket #40, lors de l'ancrage d'un mémo, tout ce qui est à gauche sont ceux dans quoi le compte rendu est ancré. dans le cas illustré par la maquette, étant donnée qu'on veut ancrer un compte rendu théorique, à gauche on doit uniquement avoir les différents comptes rendus de codage (représenté par la couleur jaune).

**Comment by AndreMarvell** [comment]
Pour résumer, je vois qu'en dehors de la proposition de @Yeahger (qui n'a finalement pas été retenue), la maquette réalisée pour cette fonctionnalité est donc validée.
La feature ***L'ajout d'ancrage à un compte rendu*** est donc prête pour un **test de recette**.

***PS:*** Cependant, pour des soucis de cohérence,  j'invite tous les membres à se référer a cette maquette comme modèle pour toutes les fonctionnalités qui implémentent un ancrage (notamment #47 et #49 ), étant donné que celle-ci a été validée par @christophe-lejeune.
 
@bj0rge @ChangruLU @ConstantSIDJUI @EdwardNjango @mchidaine @PabloPrudhommeau @salamata @Slaals @supertinou @valentin-bonino @valentinlefevre @yeahger

**Comment by sandrasongue** [comment]
Test de recette pour l'ajout d'un ancrage (l'analyse théorique) à un compte rendu théorique avec RSpec syntax :

```ruby
require 'spec_helper'
feature 'Ajouter un ancrage à un compte rendu' do
scenario 'pour un compte rendu théorique' do
visit '/'
click_on 'Ajouter des ancrages'
click_on 'Créer compte rendu opérationnel'
select 'Analyse théorique'
click_on 'Valider'
end
end

**Comment by christophe-lejeune** [comment]
@ConstantSIDJUI, les contraintes sur les types de comptes-rendus susceptibles de fournir ses ancrages à un compte-rendu théorique ne sont pas si strictes. Un compte-rendu théorique peut s'appuyer à la fois sur un compte-rendu de terrain et un compte-rendu de codage. Un exemple apparaît dans le *Manuel d'analyse qualitative*, page 54.

**Comment by christophe-lejeune** [comment]
@AndreMarvell, une amélioration mineure pourrait être apportée aux maquettes ci-dessus : la légende en bas à gauche devrait comporter les comptes-rendus de scénario en bleu.

**Comment by AndreMarvell** [comment]
Comme convenu voici la maquette modifié avec la légende dans laquelle figure le compte rendu de scénario.

![image](https://cloud.githubusercontent.com/assets/5513545/7790753/f31c67ea-0291-11e5-93fc-94aa711086a4.png)

**Comment by christophe-lejeune** [comment]
This feature needs to be refactored since commit 80f5f59be453cf667e67fda3ef5d8fc4e2fc84eb

**Comment by christophe-lejeune** [comment]
Commit bdb1c83469fffa9f0b720ff18d1a022449d508c2 implements grounding removal.
