### ISSUE TITLE
Tracer une schématisation

### ISSUE THREAD

**Issue by christophe-lejeune** [Hypertopic/Cassandre#49]
# Summary of requested features/fixes
## Diagrams

In axial coding, diagrams allow to link two dimensions/properties.
- [x] The user may create a diagram from a coding memo.
- [x] A diagram may link two properties, varying in the same direction.
- [x] A diagram may link two properties, varying in opposite directions.
- [x] A diagram may link two dimensions, varying in the same direction.
- [x] A diagram may link two dimensions, varying in opposite directions.
- [x] A diagram may link a dimension and a property.
- [x] Negative cases can be mentioned on the diagram.
- [x] The name of the diagram is generated from the name of its components.
- [x] The name of the diagram should be updated when one of its component is renamed.
- [x] Diagram's shape is not affected by the length of the component's label.
## Graphs

In selective coding, graphs allows to integrate all properties/dimensions.
- [x] The user may create a graph from a diagram
- [x] A graph is constructing by adding diagrams to its groundings.
- [x] Clicking a graph's node directs to the matching coding memo.
- [x] Clicking one graph's edge directs to the matching diagram.
- [x] Graphs should not override menu buttons.
- [x] Graph name may be modified.
# Discussion

Les **diagrammes** ou **schématisations** sont des comptes-rendus spécifiques, dont le mode de saisie est graphique (et non de texte libre). On peut en distinguer deux types : 
- Les schématisations de codage axial associent deux nœuds, soit deux bâtonnets, soit deux triangles (illustrés pages 104, 108 et 109 du _Manuel d'analyse qualitative_).  
- Les schématisations de codage sélectif (ou "schématisations finales") comportent, elles, plus de nœuds (illustrées page 118 du _Manuel_). 

Dans les deux cas, les schématisations gagneraient à être tracées au moyen d'un éditeur (ce qui présenterait plusieurs avantages sur la 'simple' importation d'images) : 
- Les utilisateurs pourraient choisir les noms des nœuds parmi les étiquettes déjà créées. Ainsi les _ancrages_ des schématisations se compléteraient automatiquement.  
- En outre, ce faisant, **cliquer sur les nœuds** de la schématisation permettrait d'aller et venir entre la schématisation et le matériau (ce type de navigation est proposée par d'autres logiciels d'analyse de textes, comme _NVivo_, par exemple). 
- L'éditeur pourrait assister l'agrégation des schématisations de codage axial en une schématisation de codage sélectif, selon les conventions explicitées pages 116-117  du _Manuel_. Agréger des diagrammes serait précieux pour l'analyste et offrirait également des possibilités de navigation supplémentaires : cliquer **sur un lien** de la schématisation finale permettrait de "remonter" à la schématisation de codage axial d'où cette articulation provient. Les _ancrages_ de la schématisation finale (s'appuyant sur des schématisations de codage axial) seraient ainsi, eux aussi, gérés par le système. 

Ce qui précède n'implique pas nécessairement de disposer d'une interface WYSIWYG : une image dotée de liens dynamiques pourrait aussi être générée à partir de la déclaration des noms de nœuds et de leurs relations.

**Comment by christophe-lejeune** [comment]
@AndreMarvell @bj0rge @ChangruLU @ConstantSIDJUI @EdwardNjango @mchidaine @PabloPrudhommeau @salamata @Slaals @supertinou @valentin-bonino @valentinlefevre @yeahger 

Le présent ticket a été créé suite à mon commentaire de la synthèse du ticket #40. Cette fonctionnalité occasionne-t-elle des questions ? Tout vous paraît-il clair ?

**Comment by EdwardNjango** [comment]
Bonjour, je vous propose cette maquette pour répondre aux besoins énoncés  par @christophe-lejeune.
Le descriptif de la maquette est à venir.

![tracerSchematisation](https://utt.mybalsamiq.com/mockups/3133300.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

**Comment by bj0rge** [comment]
J'ai complété les schématisations de type axial de @EdwardNjango 

![Articulation en forme de balance](https://utt.mybalsamiq.com/mockups/3151261.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

![Articulation en forme de curseurs](https://utt.mybalsamiq.com/mockups/3151328.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

Concernant les schématisations de codage sélectif, au vu de leur complexité relative il serait intéressant d'utiliser une interface WYSIWYG en point & click [de ce type](http://jointjs.com/rappid) (projet sous licence Mozilla Public License, v. 2.0)

**Comment by christophe-lejeune** [comment]
Les trois maquettes proposées sont bien réalisées.
* La solution proposée pour nommer les cas négatifs dans la schématisation en forme de bâtonnets est opérationnelle et simple l'utilisation. Sans doute faut-il, cependant, amender le traçage des articulations pour permettre de représenter la configuration selon laquelle les articulations (lignes pleines) sont transversales et les cas négatifs (lignes pointillées) sont horizontales.
* Une option supplémentaire devrait exister pour la schématisation des doubles curseurs : ceux-ci doivent pouvoir est soit têtes bêches `LT` (comme vous les avez représentés), soit dos à dos ` JL`.
* La schématisation en forme de balance pose des problèmes de représentation spécifiques, qui me motivent à vous inviter à laisser tomber.

**Comment by christophe-lejeune** [comment]
Deux améliorations pourraient être apportées aux maquettes ci-dessous
* La légende en bas à droite devrait comporter les comptes-rendus de scénario en bleu. 
* Le compte-rendu qui devrait apparaitre en bas à droite serait plus vraisemblablement une "schématisation globale".

**Comment by christophe-lejeune** [comment]
* Je ne sais pas ce que désigne « ajouter un coaxial » dans la rubrique « Graphiques » en haut des différentes maquettes. Si vous me décrivez la fonction que vous avez en tête, nous pourrons la baptiser ensemble de la manière la plus opportune possible. 
* Vu que le nom de la schématisation apparaît en haut, il ne me semble pas opportun de répéter ce nom, juste en dessous (sous « Propriétés »). 
* Le terme « Propriétés » revêt un sens spécialisé en qualitatif; je ne comprends pas son usage, en regard de « Graphiques » en haut de la maquette. Pouvez-vous me l'expliquer, de manière à ce que nous décidions ce qui convient le mieux à cet endroit ? 
* Est-il utile, dans la même zone, de mentionner le type « Schématisation » ? L'utilisateur voit bien de quoi il s'agit, non ?

**Comment by bj0rge** [comment]
Concernant les remarques :

- Je laisse @EdwardNjango corriger sa maquette pour correspondre à votre commentaire
- J'ai modifié les maquettes que je vous avais proposé (cf. infra) 
- Quels sont les problèmes de la représentation en balance ? Je me suis inspiré de ce qui était dans votre livre pour créer cette maquette, mais peut-être est-il possible néanmoins de proposer une version vous satisfaisant ?
- Je pense que @EdwardNjango voulait dire "Ajouter un codage axial" pour reprendre vos termes @christophe-lejeune 
- A priori, d'après la maquette, la première occurrence du nom est éditable, il s'agit donc du nom que l'utilisateur va donner à la schématisation. La seconde ne l'est pas, ce qui correspond sans doute à celui donné lors de la dernière version. @EdwardNjango, peux-tu confirmer ?
- Pour les deux derniers points je laisse @EdwardNjango répondre, c'est lui qui avait créé la première maquette contenant ces informations.

![Schématisation curseurs](https://utt.mybalsamiq.com/mockups/3151328.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

![Schématisation curseurs inversés](https://utt.mybalsamiq.com/mockups/3165311.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

**Comment by EdwardNjango** [comment]
Bonjour,
- "Ajouter un coaxial" comme @bj0rge  l'a mentionné plus haut "Ajouter un coaxial" voulait dire "Ajouter un codage coaxial", j'ai corrigé l'intitulé, je peux toujours le modifier en un autre à vous de juger. Cette fonctionnalité est disponible pour une schématisation de codage sélectif (dont je compte faire la maquette plus tard si vous n'y voyez pas d'inconvénients bien évidement).  Elle permet d'ajouter une schématisation de codage axial à une schématisation de codage sélectif. Elle permet ainsi de réaliser l'agrégation de schématisation de codage axial. Le scénario est le suivant on ajoute une première schématisation de codage axial, à l'ajout de la deuxième le logiciel détecte la compatibilité avec le premier et valide l'ajout. 
- La rubrique "Propriétés" (corrigé en "Attributs") est proposé pour présenter les différents attributs de la schématisation (nom du projet, type, date, auteur, titre), suite à vos remarques j'ai supprimé le type et le nom.
- La rubrique "Graphiques" (corrigé en "Options") propose des fonctionnalités pour les schématisations comme l'export ou l'ajout d'un codage coaxial pour une schématisation de codage sélectif
- Par rapport à vos premières remarques @christophe-lejeune,  j'ai ajouté le critère  "Horizontale" pour spécifier quelles lignes (pleine ou en pointillé) seraient tracées horizontalement, pouvez vous me dire si ce choix et les autres plus haut dans le message vous convient.



![tracer une schematisation - batonnets](https://cloud.githubusercontent.com/assets/10283167/7856198/77bade54-0527-11e5-8e49-5311b8b576f1.png)

**Comment by christophe-lejeune** [comment]
Merci pour ces contributions. 

* Les problèmes liés à la balance ne sont pas liés à notre travail. Je n'utilise plus cette représentation dans mes enseignements car elle n'apporte rien aux doubles curseurs et pose des problèmes cognitifs qui seraient un peu longs à exposer ici. Oublions-la. 

* Je comprends maintenant mieux ce que vous aviez en tête lorsque vous avez placé le bouton "Ajouter un codage axial". 
   * Compte tenu que cette fonction servira à composer les schématisations de codage *sélectif*, il ne me semble pas utile qu'elle apparaisse dans la fenêtre d'édition des schématisations de codage *axial*. 
   * Compte tenu que le codage axial désigne un ensemble d'activités, intituler un bouton "Ajouter un codage axial" est un peu étrange. Je préconise que, lorsque vous reprendrez ce bouton pour la fenêtre d'édition des schématisations de codage sélectif, vous l'intituliez "Ajouter une schématisation de codage axial".

* A priori, votre fenêtre d'édition ne permet pas le traçage de l'exemple figurant sur la maquette : en effet, l'utilisateur peut choisir si les liens horizontaux sont pointillés ou non, ce qui implique nécessairement que les liens "croisés" soient de l'autre type. La fenêtre d'édition implique donc nécessairement que la schématisation soit dotée de quatre articulations... alors que votre exemple en comporte trois. 

* C1 et C2 permettent de préciser les deux contextes des cas négatifs (symbolisés par les pointillés). Or, ces contextes ne se placent pas aux mêmes endroits selon que les articulations pointillées (cas négatifs) sont horizontales ou transversales. L'interface actuelle ne permet actuellement pas de le gérer. 

A mon avis, les deux derniers points exigent une réflexion commune : une seule solution devrait permettre de répondre en même temps à ces deux exigence.

**Comment by bj0rge** [comment]
Nous avons retravaillé avec @PabloPrudhommeau sur les maquettes des schématisation dans leur ensemble.

L'écran principal sur lequel l'utilisateur arrivera pour créer un compte rendu de schématisation est le suivant : 
![tracer une schematisation - creer un type de schematisation specifique](https://cloud.githubusercontent.com/assets/3996102/7884680/d7401346-061f-11e5-8572-238ac13048db.png)


Il peut alors choisir de créer une schématisation de codage axial ou une schématisation de codage sélectif. Il a également une prévisualisation des schématisations déjà existantes dans ce compte-rendu sur la droite, dans un panneau déroulant.

Parmi les schématisations de codage axial, il est possible de créer des schématisations de type curseur ou de type bâtonnet :
![tracer une schematisation - batonnets](https://cloud.githubusercontent.com/assets/3996102/7884549/f8458c0c-061e-11e5-9008-05b1c84f7e23.png)

![tracer une schematisation - curseurs](https://cloud.githubusercontent.com/assets/3996102/7884551/00188ace-061f-11e5-81ff-9e91a1bc3329.png)

![tracer une schematisation - curseurs inverses](https://cloud.githubusercontent.com/assets/3996102/7884552/032d6d38-061f-11e5-9dbc-f90ff38f6282.png)

Un clic sur le bouton "Annuler" ramène sur l'écran de sélection sans sauvegarder la schématisation. Un clic sur le bouton "Valider" ramène sur le même écran, mais en enregistrant les modifications.
Concernant les curseurs inversés, n'ayant aucun exemple dans le livre j'ai essayé de me figurer leur utilisation, pouvez-vous me confirmer que ce cas est correct ("plus je me trompe, plus je progresse") ?

Enfin, il est possible de tracer une schématisation de codage sélectif, nous avons pris les différents liens de couleur dans votre livre @christophe-lejeune 

![tracer une schematisation de codage selectif](https://cloud.githubusercontent.com/assets/3996102/7884579/35949e40-061f-11e5-9cc5-6c7ca21a0b7c.png)

Ces maquettes vous conviennent-elles ?

**Comment by christophe-lejeune** [comment]
Merci pour le gros travail réalisé autour de ces maquettes. Si mes commentaires sont assez longs, c'est parce que vos propositions sont nombreuses et stimulantes. Je les ventile par type de maquette. 

## Tracer une schématisation 
* Par souci de cohérence avec ce que nous avons décidé pour les autres maquettes, «Name of the project» n'a plus sa place ici. 
* La barre de titre devrait mentionner «Tracer une schématisation» et non «Rédiger un journal de bord»
* Je préconise de remplacer «Créer» par «Tracer» (tant dans les titres que dans le bouton)
* L'idée du menu déroulant me semble bonne. Je vois d'ailleurs une manière d'en tirer parti pour réduire le nombre d'étapes : il s'agirait de choisir dès cet écran la forme du diagramme. Les options possibles seraient dès lors :
   * « Articuler deux propriétés » (cette option ouvrait la fenêtre d'édition des bâtonnets)
   * « Articuler deux dimensions variant dans le même sens » (cette option ouvrait la fenêtre d'édition des curseurs "dos à dos")
   * « Articuler deux dimensions variant en sens contraire » (cette option ouvrait la fenêtre d'édition des curseurs "têtes bêches")
   * « Articuler une propriété et une dimension »
   * « Intégrer une schématisation globale »
* À la place du menu déroulant, ces options pourraient apparaître comme des boutons radio. Les cocher pourrait faire apparaître la forme en question dans la zone vide sous le bouton de validation. 
* Le terme « Catégorie » revêt un sens particulier dans le contexte de la recherche qualitative. Je propos de le supprimer.
* La zone de saisie du nom du schéma pourrait être supprimée : le nom des schématisations pourrait être déterminé par le système, de manière automatique. Ainsi par exemple, si les dimensions articulées sont « Se préserver » et « Se dépasser », le titre de la schématisation pourrait automatiquement être « Se préserver/Se dépasser ». 

## Schématisation en forme de bâtonnets
* Comme pour les autres maquettes, «Name of the project» n'a plus sa place ici. 
* La barre de titre devrait mentionner : Schématisation de Régime d'occupation et Projets intéressants.
* Ce titre devrait également remplacer «Travail et carrière»
* Si l'on suit l'idée de choisir, dans la première maquette, le type d'articulation tracée, il n'y a plus besoin de la liste déroulante permettant de choisir le type. 
* Les termes «Noeud» devraient être remplacés par «Propriété». 
* Les lignes horizontales allant par paires, il est inutile de prévoir un choix pour l'horizontale du haut et du bas. Par contre, votre proposition ne permet pas d'indiquer le contexte si jamais les horizontales étaient pointillées. Je préconise de suivre la piste suivante : 
   * Cas négatif : 
      * Articulation [ ] horiz. [ ] diag.
      * Contexte 1 : 
      * Contexte 2 : 
Si l'utilisateur ne mentionne pas le contexte d'un cas négatif, il n'apparaît pas sur le schéma. Par contre, la double ligne pleine est, elle, toujours tracée.
* Le bouton «Annuler» ne me semble pas nécessaire. En effet, si je souhaite abandonner des informations saisies dans le formulaire d'un navigateur, il me suffit de fermer la fenêtre. 
* Par cohérence avec ce que nous avons utilisé ailleurs, le bouton «Valider» mériterait de s'appeler «Enregistrer». 

## Schématisations en forme de double curseurs
* Les deux exemples (têtes bêches et dos à dos) devraient tirer parti des commentaires sur la fenêtre précédente : 
   * Il importe que la barre de titre **et** le titre à droite de «Ancrages» reflètent le contenu de la fenêtre.
   * Les boutons «Annuler» et «Valider» devraient être modifiés de la même manière que pour les bâtonnets. 
* Si l'on suit l'idée de choisir, dans la première maquette, le type d'articulation tracée, les maquettes impliquant des curseurs n'ont plus besoin de listes déroulantes, **ni** pour le type, **ni** pour la forme. 
* Les termes «Noeud» devraient être remplacés par «Dimension:» et être déplacés à l'endroit où apparaît actuellement «Nom:» 
* Un espace superflu s'est glissé entre le titre « Ancrages » et la liste des ancrages sur la fenêtre des curseurs têtes bêches. 

## Articuler une propriété et une dimension
Une nouvelle maquette devrait être proposée qui articule un bâtonnet et un triangle. 

##  Tracer une schématisation de codage sélectif
Votre maquette permet de tracer une schématisation "à partir de rien". Ce n'est vraisemblablement pas ce que feront les utilisateurs. Ils partiront vraisemblablement des articulations déjà créées et les additionneront les unes ou autres. 
* Pas besoin, dès lors de choisir les formes : les bâtonnets deviendront automatiquement des rectangles et les curseurs des losanges. L'ellipse n'est pas utile. 
* Aucun choix de couleur n'est nécessaire pour les bulles. 
* Par contre, l'interface doit permettre de choisir les articulations à intégrer parmi les schématisations disponibles ainsi que, en leur sein, les cas négatif à afficher ou non.

**Comment by PabloPrudhommeau** [comment]
Merci @christophe-lejeune pour ces nombreuses précisions. 
En collaboration avec @bj0rge, nous avons édité l'ensemble des maquettes en conséquence :
## Créér une schématisation
![tracer une schematisation - creer un type de schematisation specifique](https://cloud.githubusercontent.com/assets/11457893/8004741/912f2794-0b82-11e5-8100-fa545c4754eb.png)
## Tracer une schématisation en forme de batônnets (ou "Articuler deux propriétés")
![tracer une schematisation - batonnets](https://cloud.githubusercontent.com/assets/11457893/8004758/ab90aba8-0b82-11e5-95b8-a6d4b112efe8.png)
## Tracer une schématisation dos à dos (ou "Articuler deux dimensions variant dans le même sens")
![tracer une schematisation - curseurs inverses](https://cloud.githubusercontent.com/assets/11457893/8004776/d4a3a478-0b82-11e5-8e2f-872f8d934d13.png)
## Tracer une schématisation tête bèche (ou "Articuler deux dimensions variant en sens contraire")
![tracer une schematisation - curseurs](https://cloud.githubusercontent.com/assets/11457893/8004791/f0293be0-0b82-11e5-99ed-35e200ab392f.png)
## Tracer un schéma sélectif
![tracer une schematisation de codage selectif](https://cloud.githubusercontent.com/assets/11457893/8004855/91ad4ac4-0b83-11e5-9630-8634e5dadaaf.png)


## Modification du type de schématisation
Le lien "Changer le type de schématisation" dans les maquettes précédentes ouvre la popup suivante : 
![tracer une schematisation - curseurs_popup](https://cloud.githubusercontent.com/assets/11457893/8004819/3819fa84-0b83-11e5-88ca-dc3af37a2ab9.png)

**Comment by christophe-lejeune** [comment]
Merci pour le travail réalisé. 

Quelques commentaires sur l'ensemble maquettes précédentes : 
* Je trouve précieux et parlant que les exemples des différentes maquettes réalisées apparaissent dans la colonne de droite de la première maquette. Dans cette phase de maquettage et de démonstration, cela permet de bien appréhender les possibilités de schématisation offertes par le système. 
* Pour que l'ensemble des maquettes soient crédibles, il me semble que la barre d'adresse devrait comprendre une URL relative à une schématisation, non à la racine du service. 
* A priori, les ancrages des différentes maquettes ne sont pas encore vraisemblables. Voici comment il conviendrait de modifier chacune des maquettes : 
   * Régime d'occupation et Projets intéressants : recopier la citation du bas de la page 103 du Manuel dans un compte-rendu de terrain (respectez sa couleur). Utilisez la date mentionnée dans le Manuel et intitulez cet ancrage : « Entretien avec la DRH ». 
   * Pour « Se tromper / Progresser », mentionnez, comme ancrage :  
      * Un compte-rendu théorique (de votre cru) portant sur cette articulation. 
      * Un compte-rendu de terrain et une table des propriétés  (non-dépliés).
   * « Comprendre / Bêtise » s'appuie sur deux comptes-rendus : 
       * Un compte-rendu de terrain intitulé « Entretien conduit par Marine Leleu », dont le contenu est « Non, il lui manque quand même beaucoup. Mais là je pense que... oui il comprend quand même, il n'est pas totalement... bête. » 
       * Un compte-rendu de codage (non déplié) intitulé « Micro-analyse collective » daté du 16/11/2011. 
  * Les ancrages de la schématisation de codage sélectif ne devraient comporter que des schématisations (utilisez les vignettes de la colonne de droite de la première maquette). 
* Je ne comprends pas pourquoi l'ensemble des maquettes ont conservé le bouton «Quitter sans enregistrer». Y-a-t-il une raison particulière ? 

Voici enfin quelques commentaires sur des maquettes spécifiques :

## Schématisation de codage sélectif
* Le panneau de paramétrage devrait permettre d'ajouter des schématisation de codage axial (et non des propriétés et des dimensions isolées)

## Modification du type de schématisation
* J'aime bien la manière dont vous avez géré le basculement d'une schématisation à l'autre. Cela me semble clair. Peut-être l'option correspondant à la schématisation en cours devrait-elle grisée (car basculer d'un type à lui-même n'a pas de sens). 

C'est parce que ces maquettes devraient pouvoir être montrées publiquement que je me permets d'insister pour qu'elles soient le plus crédibles possible.

**Comment by bj0rge** [comment]
Bonjour @christophe-lejeune 

Je retravaille dès que possible pour vous fournir la dernière version, en reprenant les travaux sur l'ancrage pour unifier le visuel. C'est à cette occasion que je retravaillerai la crédibilité de la maquette (ancrages notamment, mais aussi URLs).
Concernant le bouton d'annulation, c'est par lui que nous pourrons revenir à la vue "Tracer une schématisation" ([première maquette](https://github.com/Hypertopic/Cassandre/issues/49#issuecomment-109259074)) dans le même esprit que "Consulter un compte-rendu" dans [l'unification](https://github.com/Hypertopic/Cassandre/issues/56#issue-85632195) (bouton "Retour vue synthétique").

J'ai également créé la page pour articuler une propriété et une dimension, mais pour l'instant elle ne fait que reprendre celle permettant d'articuler deux propriétés.

![tracer une schematisation - batonnets-curseurs](https://cloud.githubusercontent.com/assets/3996102/8128912/12bc96e4-1104-11e5-9d00-cfdc08ad5ce6.png)


J'attends vos remarques pour la modifier également et la rendre crédible d'un point de vue utilisateur (notamment sur les noms des propriétés/dimensions et sur les ancrages).

Merci de vos retours

**Comment by christophe-lejeune** [comment]
Le nouvelle maquette va dans le bon sens. Je ne vois qu'une chose à dire : contrairement à la propriété, la dimension ne nécessite pas de saisir deux valeurs ("haut" et "bas"). Par contre, l'utilisateur pourrait vouloir inverser le triangle (pointe en haut ou en bas) : un simple interrupteur pourrait être proposé pour occasionner cette version (en lieu et place des champs "haut" et "bas"). 

Une fois opéré cette (légère) amélioration, il me semble que l'ensemble des maquettes de ce ticket peuvent entrer dans le processus de "crédibilisation" (ancrage, URLs) et d'unification. 

Bon travail et à bientôt

**Comment by bj0rge** [comment]
Bonjour @christophe-lejeune ,

Voici les dernières maquettes suivant toutes vos recommandations.

![01-tracer une schematisation - batonnets](https://cloud.githubusercontent.com/assets/3996102/8233113/d8b169ea-15d4-11e5-88ca-e91b0b2cef7b.png)

![02-tracer une schematisation - batonnets-curseurs](https://cloud.githubusercontent.com/assets/3996102/8233115/d8b35a84-15d4-11e5-894a-346cb8dfc32a.png)

![03-tracer une schematisation - curseurs](https://cloud.githubusercontent.com/assets/3996102/8233118/d8b6172e-15d4-11e5-8379-d504435d0eab.png)

![04-tracer une schematisation - curseurs_popup](https://cloud.githubusercontent.com/assets/3996102/8233114/d8b36290-15d4-11e5-981c-f02a12ddda3d.png)

![05-tracer une schematisation - curseurs inverses](https://cloud.githubusercontent.com/assets/3996102/8233116/d8b3aca0-15d4-11e5-9086-c123f8996122.png)

![06-tracer une schematisation de codage selectif](https://cloud.githubusercontent.com/assets/3996102/8233117/d8b42220-15d4-11e5-9f8b-3c10fa02e742.png)
