### ISSUE TITLE
Afficher la liste des journaux de bord

### ISSUE THREAD

**Issue by supertinou** [Hypertopic/Cassandre#52]
# Required features
- [x] List all diaries.
- [x] Diary's icon features badges counting number of memos.
- [ ] Diary's icon features badges counting number of contributing users.
- [x] Filter diaries according to user access.
# Description

Cette fonctionnalité permet d'afficher la liste des journaux de bord et peut constituer la page maitre de l'application. A partir de cette page on peut : 
- consulter ses propres journaux de bord.
- consulter les journaux dont l'utilisateur est collaborateur.
- consulter les journaux récent (modifié/crée récemment)
- créer des journaux de bord (#53)
# Fonctionnalité
## Scénario

Sera présent sur l'interface : 
- un volet principal à droite affichant des dossiers pour journaux de bord
- Un volet à gauche affichant une icone permettant de créer un nouveau journal (#53) et de filtrer les journaux que l'on souhaite faire apparaitre sur le volet principal : Tous, Récent, Les miens, ceux auquel je collabore, ...
## Maquette

![maquette](https://utt.mybalsamiq.com/mockups/3086262.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

**Comment by valentinlefevre** [comment]
@supertinou Juste histoire de faire avancer un peu l'issue, les icônes des projets pourraient-ils ressembler à un livre, pour se rapprocher du concept de journal de bord?

Est ce qu'on envisage l'affichage, via de petites pastilles de couleur sur les journaux de bord, du nombre de collaborateurs dans un projet, du nombre d'entrée dans le journal en question?

**Comment by christophe-lejeune** [comment]
* L'idée d'une icône rappelant le type de document auquel on se réfère me plaît bien. Il s'agirait alors plutôt d'un "carnet à spirale" que d'un livre. 
* J'aime bien l'idée des pastilles. Je vous laisse avancer là-dessus pour voir ce que cela va donner.

**Comment by Slaals** [comment]
## Proposition 

___

![ScreenShot](https://utt.mybalsamiq.com/mockups/3086262.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

## Details

___

Pas grand chose à dire. Les ronds rouges sont pour les nombres d'entrées (comptes rendus) dans le journal. Les ronds bleus quant à eux sont relatifs au nombre de collaborateur.

**Remarque** : Le journal de bord BTP n'a pas de rond bleu ! C'est la situation où il n'y a aucun collaborateur, je vois pas l'intérêt de mettre un 0 si ce n'est perturber l'utilisateur. Ceci dit, je pense qu'il serait pertinant de laisser un rond rouge même dans le cas où il n'y a aucune entrée ! Dans cette situtation on informe tout de même qu'il s'agit d'un journal de bord vide, et ça resterait évident aux yeux de l'utilisateur.

**Comment by christophe-lejeune** [comment]
Quelques réflexions au sujet de la terminologie utilisée dans la maquette. 
* La réflexion sur les pastilles rouge et bleu me semble aller dans le bon sens. Attention cependant qu'un journal de bord qui comprend trois comptes-rendus ne peut être dotés de zéro participants. Si trois comptes-rendus ont été rédigés, ils l'ont été par quelqu'un. Même si c'est l'utilisateur en question qui visualise la liste des journaux de bord, nous n'en sommes pas à 0 mais à 1 participant. La réflexion de @Slaals reste cependant opportune dans ce cas de figure : l'absence de pastille ne signifie cependant pas 0 mais 1 seul participant. Cela implique donc que les pastilles n'apparaissent que dès qu'une deuxième personne participe.    
* Le panneau latéral distingue « tous les projets », « mes projets » et « les projets auxquelles je participe ». Comme indiqué dans la discussion #53, je ne vois pas bien la nécessité de distinguer mes projets de ceux auxquels je participe. Deux options au lieu de trois me semblent donc suffire.
* La maquette gagnerait également à tirer parti de ce que nous avons discuté dans le ticket #53 au sujet de l'opportunité de parler de « projet ».
* Je persiste à penser qu'un carnet à spirale serait plus évocateur qu'un livre.

**Comment by supertinou** [comment]
Maquette mise à jour : 

![](https://utt.mybalsamiq.com/mockups/3086262.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

**Comment by christophe-lejeune** [comment]
Micro point de détail :  « Journaux au**x**quel**s** je participe »

**Comment by supertinou** [comment]
*Maquette corrigée.*

**Comment by ltosi** [comment]
Ajouter une infobulle qui indique la signification des pastilles?

**Comment by valentin-bonino** [comment]
J'ai retravaillé la maquette car le système des pastilles ne convenait pas à tout le monde, faisant plus penser à des notifications.
Je me suis permis de proposer des solutions différentes pour chacun des journaux présents dans la maquette, et également une légende en bas si cela peut convenir. Il ne reste plus qu'à en choisir une.

![mock up](https://utt.mybalsamiq.com/mockups/3086262.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

**Comment by christophe-lejeune** [comment]
Je ne sais pas exactement quels problèmes soulèvent les pastilles... Mais il est vrai que la proposition apparaissant pour le premier journal (Locomotives) est peut-être plus partante. S'il n'y a pas d'objection, je propose d'adopter celle-là. 

NB: Pour plus de lisibilité, le sticker blanc peut-être supprimé du carnet.

**Comment by christophe-lejeune** [comment]
I did not close this issue earlier because all the required features listed in the first post were not created yet. Closing an uncompleted issue might conceal that some work has to be done

**Comment by benel** [comment]
Sorry for closing it then. I have been more cautious for other similar issues.
