### ISSUE TITLE
Voir de manière synthétique le journal de bord

### ISSUE THREAD

**Issue by PabloPrudhommeau** [Hypertopic/Cassandre#54]
But du ticket
===
Le but de ce ticket est de mettre en avant une fonctionnalité un peu délaissée qui a été évoquée la première fois pendant la séance du TD 23/05/2015 de 8h à 10h avec VB. En raison d'un grand nombre de ticket, cette issue ne vas pas être détaillée. Pour l'instant, cette issue servira dans un premier temps à
- Informer @christophe-lejeune de cette idée, pour que l'on puisse avoir un feedback de sa part
- Nous permettre de classer ce ticket dans les tâches prioritaires ou non prioritaires 

Synthèse des besoins
===
Il a été évoqué le besoin d'avoir une vue extrêmement synthétique et globale de l'ensemble du journal de bord. Cette vue synthétique permettrait à la fois de naviguer au sein de l'ensemble du journal de bord et de consulter de manière global celui-ci (de voir l’avancement de certaines tâches par exemple, ou même de voir qui a participé à quelle partie du journal de bord via un système de couleur).
Cette vue globale ressemblerait à une sorte de carte qui permettrait à l'utilisateur (pas forcément à l'aise avec le cheminement des différents compte-rendus, ou de la navigation en général) de s'orienter facilement dans le journal de bord.

**Comment by supertinou** [comment]
:+1: #55 Concerne l'affichage d'un journal de bord sous forme d'un arbre des comptes rendu à partir des ancrages et sous forme de liste filtrable et permet donc de naviguer parmis les compte rendus. 
Par contre, ne propose pas de solution pour les autres fonctionnalités qui permet de voir l'activité du journal de bord, comme les exemples que tu as proposé (voir qui a participé à quelle partie du journal de bord via un système de couleur)
@PabloPrudhommeau, qu'entends-tu par "voir l’avancement de certaines tâches" ?

**Comment by christophe-lejeune** [comment]
Comme je l'ai évoqué précédemment https://github.com/Hypertopic/Cassandre/issues/45#issuecomment-94307438, disposer d'une cartographie des comptes-rendus du journal de bord me semble utile. J'ai l'impression que c'est ce que visent à la fois #54 et #55. Quelle différence distingue ces deux propositions ?

**Comment by PabloPrudhommeau** [comment]
J'ai effectivement complètement loupé ton ticket qui semble remplir en grande majorité les besoins que je voulais évoquer... Désolé.

@supertino, ~~l'avancement des tâches~~ évoquait en réalité **l'avancement dans le processus de rédaction des différents compte-rendus** (Terrain, codage, théorique, opérationnel, etc.). Dans l'idée, cet avancement n'était pas vraiment une fonctionnalité mais une finalité, je m'explique : Cette fameuse "carte" permettrait de visualiser de façon très globale l'ensemble des compte rendus et par extension l'avancement du processus de rédaction des différents compte-rendus. Pourquoi ? C'est très simple. Imaginons que cette carte soit organisée de la façon suivante : 
* Les compte rendus sont classés horizontalement en fonction de leur type (Terrain, codage, théorique, opérationnel, etc.)
* Les compte rendus sont classés sur l'axe horizontal en fonction de leur date.
De cette manière,plus l'on descend dans la carte, plus les éléments du journal de bord seront récents. Pareillement, plus l'on navigue à droite de la carte, plus l'on avance dans le processus de rédaction des différents compte-rendus. 

##### Ceci dit...
Avec un peu de recul, je pense que notre solution est beaucoup moins pertinente et dynamique que la tienne @supertinou car en prenant l'exemple simple où un compte rendu de terrain donne 2 comptes rendus de codages rédigés l'un après l'autre, ces 2 derniers ne seraient plus affichés sur la même ligne, mais l'un en dessous de l'autre... Pour continuer l'exemple, si on rédige un deuxième compte-rendu de terrain qui donne 3 comptes rendus de codages, on consolide cette joyeuse pagaille. Si tu as besoin de plus d'explications je pourrais fournir un schéma.


##### Pour conclure...
Notre concept aurait pu être viable si pour 1 compte rendu de terrain, on avait 1 compte rendu de codage, 1 compte rendu théorique, 1 compte rendu opérationnel, 


##### Ticket à fermer ?
Je pense que ce ticket présente à la fois une idée moins pertinente est qui s'avère être un doublon de #55 que tu as créé avant moi. Nous devrions donc peut être le fermer :)

**Comment by supertinou** [comment]
> J'ai effectivement complètement loupé ton ticket qui semble remplir en grande majorité les besoins que je voulais évoquer... Désolé.

Tu n'as pas pu le voir puisque nous avons rédigé le ticket en même temps sans ce concerter.Je voulais le faire avant votre TD mais malheureusement ça s'est chevauché. C'est plutôt à moi de m'excuser de t'avoir fait travailler sur quelque chôse que tu aurais pu éviter. :v: 

> Les compte rendus sont classés horizontalement en fonction de leur type (Terrain, codage, théorique, opérationnel, etc.)


>Les compte rendus sont classés sur l'axe horizontal en fonction de leur date. 

- J'imagine que tu voulais dire vertical ?
- En fonction de la date de dernier accès / modification ?

>De cette manière, plus l'on descend dans la carte, plus les éléments du journal de bord seront récents. Pareillement, plus l'on navigue à droite de la carte, plus l'on avance dans le processus de rédaction des différents compte-rendus.
>Si tu as besoin de plus d'explications je pourrais fournir un schéma.

Je vois l'idee. Si tu es partant, ça serait intéressant d'avoir un schéma de cette possibilitée d'affichage du graphe des comptes-rendus. Comme ça on pourra comparer et discuter de la meilleure option. Oui si tu veux tu peux fermer ton ticket #54 et on continue sur le #53.
Tu peux proposer le schéma d'affichage et tes idées seront intéressantes.

**Comment by benel** [comment]
Suite de la discussion : ticket #55.
