### ISSUE TITLE
Voir de manière synthétique le journal de bord

### ISSUE THREAD

**Issue by supertinou** [Hypertopic/Cassandre#55]
# Required features
- [x] Draw a graphical network of groundings between memos, diagrams and graphs.
- [x] Quote (" & ') are allowed in memo name.
# Afficher un journal de bord
## Description

Cette fonctionnalité permet d'afficher un journal de bord.
Elle permet d'afficher la liste des compte rendus du journal de bord sous forme de graphe et sous forme de liste filtrable.
### Scénario

Sur l'interface, il est possible 
- de modifier le journal de bord (la liste des collaborateurs, le nom) via l'icone de roue crantée.
- sur le volet de gauche  (qui se déplie se cache ou s'affiche pour profiter de l'espace entier) de faire une recherche sur les comptes-rendus
- sur l'espace de droite, de consulter l'arbre des comptes rendus (créee à partir des ancrages) et d'accéder au contenu d'un compte rendu en cliquant dessus.
### Maquette

**Version verticale :**
![journal](https://utt.mybalsamiq.com/mockups/3087361.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

**Version horizontale :**
![journal](https://utt.mybalsamiq.com/mockups/3130870.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

**Comment by christophe-lejeune** [comment]
Quelques remarques sur la maquette : 
* La ressource de la plateforme Balsamiq de l'UTT est inaccessible. 
* Disposer d'une telle cartographie m'apparaît particulièrement opportun !
* J'aurais personnellement organisé les liens de droite à gauche, plutôt que de haut en bas. Ce n'est peut-être que du détail... ou pas. N'hésitons pas à discuter ce point. 
* Je ne vois pas directement l'utilité du panneau de gauche
* Les différents types de compte-rendu pourraient être signalés par la couleur des bords de l'icône. 
* Dans la mesure où les comptes-rendus opérationnels peuvent préparer la conduite du terrain (et donc être suivis d'un compte-rendu de terrain), il pourrait être opportun de prévoir une flèche "montante". Du coup, il ne s'agit plus exactement d'un arbre. N'hésitons pas non plus à échanger là-dessus. 
* Un cas de figure non représenté me semble devoir être envisagé. Le compte-rendu de scénario descriptif sur le vécu des acteurs prépare le retour vers le terrain. C'est à ce compte-rendu de scénario, en particulier, que les acteurs peuvent être invités à réagir. Trois options s'offrent à nous quant à l'affichage de leur réaction sur la carte : 
    * Soit leurs "commentaires" apparaissent en tant que tel, comme des comptes-rendus particuliers
    * Soit leurs "commentaires" occupent la même place que les comptes-rendus de terrain (en haut). Il faut alors aussi prévoir une flèche montante
    * Soit on ne les affiche pas sur cette carte. 

Ces maquettes sont stimulantes ! 
À bientôt pour la suite.

**Comment by supertinou** [comment]
> "La ressource de la plateforme Balsamiq de l'UTT est inaccessible."

C'est seulement le lien pour éditer la maquette. Vous n'avez pas de compte sur le balsamiq de l'utt.

> "J'aurais personnellement organisé les liens de droite à gauche, plutôt que de haut en bas."

Vous voulez dire que vous auriez organisé les liens fléchés des comptes rendus de gauche à droit et non de haut en bas ?Avez vous une raison particulière de préférer cette option ? Il faudrait peut être voir avec un exemple d'ancrage de comptes-rendus. Avez-vous un exemple d'ancrages de comptes-rendus à nous fournir ? pour que nous voyons à quoi ressemblerai un ensemble d'ancrage complet?

> "Je ne vois pas directement l'utilité du panneau de gauche"

Il est vrai que l'affichage des documents sous forme de liste n'est pas réellement utile car nous les voyons sous forme d'arbre mais je pense que la fonction de recherche est intéressante pour rechercher un compte rendu dans un arbre assez-complexe. Cette liste ce justifie donc pour afficher la liste filtrée des documents, elle est inutile si on trouve un autre moyen d'afficher dans le graphe que les documents que l'on recherche. 
- Peut être que cette liste ne devrait être afficher uniquement lorsqu'on appuie sur un bouton ouvrant le volet de recherche ?

> Les différents types de compte-rendu pourraient être signalés par la couleur des bords de l'icône.

En effet, on peut indiquer les couleurs que vous avez avez indiqués : 

| Compte rendu | Couleur |
| ------------- | ------------- |
| Terrain         |  noir        |
| Codage       | jaune      | 
| Théorique    | vert         |
| Opérationnel | mauve |

Après, on peut discuter des détails de choix de : 

- mettre un sous titre avec le type de document ?
- laisser les abréviations T, Cd, Th, Op ?
- afficher un popup au survol du document pour expliciter quel est le type de document ?
- afficher une légende de couleurs pour les types sur la page ?

>"Dans la mesure où les comptes-rendus opérationnels peuvent préparer la conduite du terrain (et donc être suivis d'un compte-rendu de terrain), il pourrait être opportun de prévoir une flèche "montante". "

Absolument, il faudrait inclure cet exemple dans la maquette. D'ailleurs encore une fois si vous avez un exemple concret de comptes-rendus ancrées à nous fournir, cela serait assez intéressant.

> Concernant le compte-rendu de scénario descriptif sur le vécu des acteurs :
 
Dans le graphe des ancrages des différents types de comptes-rendus de la page 123 du manuel d'analyse qualitative :
![ancrage des différents types de comptes-rendus](https://cloud.githubusercontent.com/assets/10283167/6899296/d01f89a6-d6ff-11e4-83df-d457471c5e28.jpg) On voit bien qu'un __compte-rendu de scénario descriptif sur le vécu des acteurs__ se base sur une schématisation car celle-ci facilite l'identification des éléments centraux qui méritent d'intégrer le récit.
- D'autre part, un compte rendu de terrain peut être lié directement à un compte rendu descriptif des acteurs. Pourquoi ?

*Quelques informations sur les comptes-rendus descriptif des acteurs, page 120 :*

> - Le texte de ce compte rendu raconte l'histoire des informateurs rencontrés, en une demi page. Un texte assez court et simple. La concision du récit oblige à identifier le coeur de de l'analyse et aller à l'essentiel. Il doit être compréhensible par votre grand mère. Cela permet au chercheur la clarification de l'expression de sa pensée. 
- Les versions successives sont conservés dans le carnet de bord. Elle documentent la progression de l'écriture ainsi que les raison des corrections.
- Le chercheur organise une "restitution" en soumettant ce condensé d'analyse aux informateurs rencontrés afin de mettre à l'épreuve sa pertinence. Il demande à chacun de ses interlocuteurs s'il se reconnait dans l'histoire proposée. __La réaction de l'informateur est enregistrée et son retour affine, amende ou conforte les analystes du chercheur.__
- La nouvelle version amendée sert alors aux rencontres suivantes. L'analyste corrige le compte rendu de scénario descriptif 
- Si le retour met plus en cause le compte rendu, le problème soulevé est discuté dans un nouveau compte-rendu théorique qui sert de base à l'élaboration de la nouvelle version du compte rendu de scénario descriptif.

-

>C'est à ce compte-rendu de scénario, en particulier, que les acteurs peuvent être invités à réagir. Trois options s'offrent à nous quant à l'affichage de leur réaction sur la carte :
Soit leurs "commentaires" apparaissent en tant que tel, comme des comptes-rendus particuliers
Soit leurs "commentaires" occupent la même place que les comptes-rendus de terrain (en haut). Il faut alors aussi prévoir une flèche montante
Soit on ne les affiche pas sur cette carte.

Avant de pouvoir proposer des solution à ces questions, pouvez nous expliquer comment gérez vous le retour des informateurs sur votre journal de bord ? Peut être avec un exemple concret ? 

- Créez vous un compte rendu de terrain pour collecter leur commentaires après avoir fait un entretien avec eux ? (avec pour ancre le compte rendu descriptif) 

- A quoi sert sert ces commentaires ? A créer une nouvelle version de l'analyse descriptif du vécu des acteurs ? 

- Pouvons nous imaginer l'utilité d'envisager et penser à pouvoir collecter les retours des informateurs directement via un accès partagé au document d'analyse descriptif et un mécanisme de collecte d'information via l'application ?

Un autre détail concernant l'historisation :
- Comment historisez vous les modifications successives du compte rendu descriptif (comme indiqué dans le manuel d'analyse qualitative "*Les versions successives sont conservées dans le carnet de bord*" ? J'imagine qu'il est assez compliqué de le faire sur papier car vous n'allez pas recopier à chaque fois ce que vous avez écrit et faire plusieurs versions mais en informatique il est possible de le faire. Par exemple https://gist.github.com fait des différentes version d'un document très facilement et les affiches façilement.

Conscient qu'il y'a beaucoup de questions attendant beaucoup de réponses. Je tacherais de garder un résumé à jour en entête de la fonctionalitée avec le résumé brefs des choix et questions et des modifications des maquettes.

**Comment by christophe-lejeune** [comment]
Voici quelques éléments de réponse aux questions sur le compte-rendu de scénario descriptif sur le vécu des acteurs. 

* Les qualitativistes ont l'habitude d'organiser une "restitution" auprès des acteurs qui ont participé à une recherche. Cela peut prendre la forme d'un entretien (ce qui explique le lien avec un compte-rendu de terrain), de la publication dans un bulletin de liaison ou d'un événement (avec présentation et apéritif dinatoire). 

* Ce type de *feedback* entend effectivement recueillir l'avis des premiers intéressés. L'informatisation de ces retours est largement traitée dans #41 et #45. 

* Le compte-rendu de scénario descriptif sur le vécu des acteurs constitue le contenu de cette restitution. S'agissant d'une synthèse, je rédige un tel compte-rendu sur ordinateur. J'ai l'habitude d'en conserver les différentes versions par simple copier-coller dans un même document. 

@supertinou, que puis-je encore clarifier ?

**Comment by christophe-lejeune** [comment]
Voici les raisons qui plaideraient en faveur d'un affichage de la succession des comptes-rendus de gauche à droite. Cette option adopterait les conventions de lecture suivantes, relativement intuitives, me semble-t-il. 
* La succession des comptes-rendus de gauche à droite correspond au sens de lecture d'un texte et à la façon usuelle de représenter une ligne du temps.
* Cette métaphore horizontale impliquerait d'afficher les comptes-rendus de terrain les uns en dessous des autres, ce qui correspond à la **liste** des contacts avec le terrain.
* Ce mode de visualisation est utilisé pour parcourir le journal de bord #47 et éditer les ancrages d'un compte-rendu #48.

Si l'on dédie une couleur à chaque type de compte-rendu, il ne me semble pas utile de répéter leur type sous l'icône. Par ailleurs, je ne suis pas sûr que la légende des couleurs soit obligatoire. L'idée de la mention du type lors du survol est tentante. Quoi qu'il en soit, je donne ici un avis d'utilisateur parmi d'autres. Certains collègues sont sans doute plus qualifiés que moi en matière d'IHM. 

Voici, comme demandé, un exemple supplémentaire d'entête de comptes-rendus. 

Projet | La communication et les interactions sur les communautés de marque en ligne
:-------|:------------------------------------------------
Type | Compte-rendu de scénario analytique
Auteurs | Fanny Fox, Anaïs Gretry, Pascal Heins, Salvatore Loria
Date | 22/04/2014
Ancrages | Comptes-rendus théoriques « Réflexion théorique suite à l’entretien A » du 02/01/2014 ; « Une famille désunie de l’entretien B » du 11/03/2014 ; « Conceptualisation de catégories (tables des propriétés) » du 18/03/2014 ; « Comparaison à des cas dissemblables » du 19/04/2014 ; « Identification et schématisation des liens entre propriétés/catégories » du 22/04/14 ; « Schématisation de codage sélectif » du 22/04/14 : « Identification et schématisation des liens entre propriétés/catégories (suite) » du 22/04/14. « Cas dissemblable : le comportement des consommateurs dans le secteur de la prostitution » du 22/04/14. Compte-rendu de terrain « Impressions après la transcription de l’entretien B » du 2/03/2014. Compte- rendu de codage « Impressions après l’étiquetage de l’entretien B » du 11/03/2014 ; « Étiquettes de l’entretien B » du 11/03/2014.

**Comment by christophe-lejeune** [comment]
@ltosi, existe-t-il des préconisations en matière d'IHM qui plaideraient en faveur d'un affichage vertical (maquette ci-dessus) ou horizontal (ma dernière contribution, ci-dessus) ?

**Comment by mchidaine** [comment]
![](https://utt.mybalsamiq.com/mockups/3130870.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

Avec @salamata nous proposons une nouvelle maquette pour la vue synthétique, orientée de gauche à droite.
On a une vue synthétique des comptes rendus avec les couleurs différentes pour chaque type de compte rendu.

On a également une recherche avancée qui permet de chercher un compte rendu spécifique selon son type et son auteur par exemple. 

Nous proposons que le compte rendu le plus récent s'affiche en haut sur le tableau de bord pour que l'on puisse voir plus facilement les dernières modifications.

**Comment by christophe-lejeune** [comment]
Merci pour cette maquette ! 

Quel espace désigne exactement le « tableau de bord »? S'agit-il d'un espace évoqué dans un autre ticket ?

Je pose la question sans malice, à simple fin de clarification.

**Comment by salamata** [comment]
Je dirais que l'ensemble constitue le tableau de bord avec un espace de recherche intégré à droite afin de pouvoir visualiser un anciens compte-rendu par exemple.

**Comment by christophe-lejeune** [comment]
Si la deuxième maquette (horizontale) s'appuie sur le sens de l'écriture (gauche à droite, haut en bas), alors le dernier compte-rendu devrait plutôt se retrouver en bas à droite du "tableau de bord". 

Cette convention s'écarte cependant de ce que l'on trouve dans les blogs, mails et forums, affichant la contribution la plus récente en haut de la page.

Peut-être @ltosi est-elle en mesure d'éclairer le choix en faveur d'un affichage vertical (première maquette) ou horizontal (deuxième maquette) ainsi que de la représentation du temps à l'écran (ce qui nous aiderait à situer le dernier élément).

**Comment by ChangruLU** [comment]
![vue verticale de journal de bord](https://cloud.githubusercontent.com/assets/11457739/7769219/125f0610-0082-11e5-9b7e-92acabafca61.png)



![vue horizongtal de journal de bord](https://cloud.githubusercontent.com/assets/11457739/7769203/0361e934-0082-11e5-826f-da4bcc50cbac.png)


@christophe-lejeune ,bonjour Monsieur, j'ai refait le maquette pour deux vues différentes(horizontale et verticale) avec la date remarquée au dessous de chaque compte-rendu. En plus, vous pouvez aussi faire une recherche avancée par la date(c'est une proposition).

Dites-nous, vous préférez plutôt la vue horizontale ou verticale ou les deux(peut être que l'on puisse faire les deux.), svp? Merci beaucoup et bonne journéé!

**Comment by christophe-lejeune** [comment]
Merci pour ces deux maquettes qui vont nous permettre de comparer et donc d'évaluer les apports deux modes de visualisation. Je me permets de vous suggérer les modifications suivantes.

* La micro-analyse constitue le tout premier compte-rendu de codage (en jaune); il ne peut donc pas apparaître en troisième position. Je suggère simplement de renommer les comptes-rendus de codage de la manière suivante : 
   * «Analyse de je ne fonctionne plus» devient «Micro-analyse de je ne fonctionne plus». 
   * «Analyse du soi intérieur» devient «Se préserver».
   * «Micro-analyse de la bureaucratie» devient «Jouer les bureaucrates».
* Je suppose que le compte-rendu en rose, sur la première maquette, correspond à un compte-rendu opérationnel. Est-ce bien le cas ? Si oui, je préconise de le baptiser, «sans titre» étant peu parlant. Je propose, à la place : «Explorer les stratégies pour se préserver». 
* Les deux flèches "montantes" de cette icône rose représentent une impossibilité logique. Il est important de conserver des flèches montantes, mais leur destination doit avoir un sens. Je propose que ces deux flèches remontent vers la droite, et non la gauche. Elles aboutiraient donc respectivement au deuxième entretien (en noir) et au dernier compte-rendu de codage (en jaune).    
* L'entretien avec le ministre gagnerait à devenir un «Entretien avec Luc» et à être doté d'une date postérieure à celle du compte-rendu rose. 
* Les dates des deux comptes-rendus qui découlent du deuxième entretien devraient évidemment être adaptées en conséquence. 
* Afin de voir si c'est lisible, il serait intéressant de disposer d'un compte-rendu théorique reposant sur des comptes-rendus de codage de différents entretiens. Pour se faire, je préconise de renommer l'«analyse de la bureaucratie» en «table des propriétés» et d'y ajouter un flèche (descendante) venant de «Se préserver».

Enfin, je trouverai particulièrement utile, une fois que la première maquette sera corrigée en fonction des suggestions ci-dessus, d'adapter la deuxième maquette pour qu'elle représente le même journal de bord. Cela permettrait, me semble-t-il, de disposer de deux maquettes réalistes et comparables. 

Afin d'éviter un travail trop important, vous pouvez évidemment me soumettre la première maquette pour validation, avant d'entamer la modification de la deuxième.

**Comment by christophe-lejeune** [comment]
Si je puis me permettre d'ajouter deux requêtes relative à la correction des maquettes, je préconise de retirer le mot "date" devant les dates (leur statut de dates étant évident) et à cadrer les nouvelles maquettes de la même manière qu'au début de ce ticket, afin que nous disposions de belles maquettes, larges (et non pas de petites maquettes au milieu d'une grille).

**Comment by christophe-lejeune** [comment]
Tant que nous y sommes : 
* Ajoutez un trait d'union à « comptes-rendus » en haut de la fenêtre
* Ajoutez « scénario », sous « opérationnel » dans le panneau latéral
* Supprimez l'espace superflue, dans la date du panneau latéral

**Comment by christophe-lejeune** [comment]
En plus des deux maquettes ci-dessus, voici une présentation alternative, en liste, présentant l'avantage d'afficher en haut de page le dernier compte-rendu ajouté. Je la fournis pour deux raisons : 
1. Cette présentation reprend l'exemple de journal de bord demandé, ainsi que les différents ancrages. Elle peut donc inspirer le traçage des autres maquettes. 
2. Il s'agit en outre d'un mode de navigation non graphique, donc plus synthétique, vers lequel l'utilisateur pourrait éventuellement basculer à partir de la navigations graphique. 

* Entretien avec Jean
* Table des propriétés
    * Se préserver
         * Autobiographie de Bart
    * Jouer les bureaucrates
        * Entretien avec Luc
* Explorer les stratégies pour se préserver
      * Fonctionner au travail
         * Micro-analyse de «je ne fonctionne plus»
           * Autobiographie de Bart

Évidemment, cette navigation en liste ne permet pas de représenter les relations "montantes" aussi clairement que la représentation graphique.

**Comment by supertinou** [comment]
![journal](https://utt.mybalsamiq.com/mockups/3087361.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

Voici la maquette d'affichage synthétique d'un journal de manière verticale mise à jour, selon vos remarques.

Je me suis permis de fusionner la recherche simple avec la recherche avancé étant donné que ceux-ci sont affichés dans le même volet gauche, il me semble que cela a peu d'interet. J'ai ajouté un champ "nom" pour préciser le nom d'un compte rendu dans la recherche.

**Comment by supertinou** [comment]
Il peut être intéressant de proposer cette alternative d'affichage. A discuter. Notez que j'ai bien suivi tous les points pour mettre à jour la vue graphique mais qu'il ne se correspondent pas. En attente de vos retours pour modifier en conséquence.

- Il est aussi possible de proposer un affichage tabulaire avec les ancrages et les référencements :

Compte-rendu | Ancrages | Référencements
------------ | ------------- | -------------
__Autobiographie de M Bart__ <br /> *01/01/2014* | :heavy_multiplication_x:   | - Micro analyse de je ne fonctionne plus <br /> - Se préserver | 
__Micro analyse de je ne fonctionne plus__ <br /> *03/01/2014* | - Autobiographie de M Bart   | - Fonctionner au travail | 
__Se préserver__ <br /> *03/01/2014* | - Autobiographie de M Bart   | - Table des propriétés | 

Enfin, tout celà montre bien que l'affichage sous forme de graphe est beaucoup plus synthétique que tout autre vue car on voit rapidement les différent comptes-rendus et les relations entre eux.

**Comment by christophe-lejeune** [comment]
Merci à @supertinou pour ses deux contributions. Elles démontrent que le mode graphique est le plus clair et le plus synthétique. 

Convaincu (comme @mchidaine et @salamata) que l'utilisateur aura à cœur d'accéder rapidement aux derniers comptes-rendus, je maintiens cependant que la liste présente également des avantages.

Quoi qu'il en soit, pour avancer sur l'affichage graphique (qui nous occupe en ce moment), je me permets de suggérer les corrections suivantes à la dernière maquette proposée : 
* renommer la « table des propriétés » en « Jouer les bureaucrates »
* renommer la « hiérarchie bureaucratique » en «Table des propriétés »
* déplacer, en conséquence, les flèches partant de « Se préserver » et de « Explorer les stratégies pour se préserver »
* ajouter l'« Entretien avec Jean » à droite des autres comptes-rendus de terrain
* dans le panneau latéral, remplacer « Nom » par « Titre ».

**Comment by supertinou** [comment]
Voici la maquette d'affichage synthétique d'un journal de manière verticale mise à jour suite à vos commentaires et pour refléter la liste de https://github.com/Hypertopic/Cassandre/issues/55#issuecomment-105008677.
En attente de votre validation.

![journal](http://cl.ly/image/1w0M2G1n2j0M/imagejiur.png)


 Une question qui concerne aussi #50 : De quel type de compte rendu fait partie une "table de propriétés" ?

**Comment by christophe-lejeune** [comment]
* La flèche "montante" allant de "Explorer les stratégies pour se préserver" vers l'"Entretien avec Luc" a disparu avec la dernière correction de la maquette. Compte tenu de son importance pour appréhender un journal de bord, je vous invite à la restaurer, même si cela vous oblige à croiser deux flèches. L'ajout de cette flèche montante permettra en outre de comparer la lisibilité des deux maquettes (horizontale et verticale). 
* L'entretien avec Luc sera vraisemblablement conduit quelques jours plus tard. 
* La table des propriétés est un compte-rendu théorique (c'est pour cette raison qu'elle apparaît en vert).

**Comment by ConstantSIDJUI** [comment]
@Super-tinou dans la description du feature Afficher un journal de bord, on doit avoir l'option modifiér un journal de bord qu'on ne retrouve pas sur la maquette.
Et aussi pour la cohérence avec les autres features sur le journal de bord, on doit avoir une légende à gauche et en bas de l'écran représentant les différents mémos associés aux couleurs.

**Comment by christophe-lejeune** [comment]
La présente fenêtre permet de visualiser le journal de bord et d'y naviguer. Je ne suis pas convaincu qu'il soit nécessaire d'y introduire des options de modification. Si l'utilisateur souhaite modifier ou ajouter un compte-rendu, il lui suffit de sélectionner un compte-rendu. Il arrive alors sur une fenêtre (#40) permettant la modification.

**Comment by christophe-lejeune** [comment]
@supertinou, pourriez-vous exposer ce qui vous a incité à rebaptiser le haut du panneau de gauche (de «Locomotive» à «Journal "Locomotive"») ?

**Comment by supertinou** [comment]
Voici la maquette horizontale mise à jour : 

![journal](https://utt.mybalsamiq.com/mockups/3087361.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

- J'ai décalé la date de l'entretien avec Luc pour qu'il soit conduit quelques jours plus tard.
- J'ai rechangé le nom du panneau gauche pour "Locomotive" à la place de "Jounal 'Locomotive'" car il n'y-a aucune justification particulière à prefixer le titre de "Journal" puisque nous sommes dans le journal.

Autre points :

- Il serait surement intéressant de mettre à disposition 3 icones : une permettant de zoommer dans le graphe, une pour de-zommer et une pour cadrer automatiquement le graphe à la zone disponible : [ + ], [ - ], [ [ ] ]
- A défaut d'une légende, afficher une tooltip au survol de l'icone d'un compte-rendu pour indiquer son type.

**Comment by mchidaine** [comment]
Voici la même maquette mise à jour mais en version horizontale : 
![](https://utt.mybalsamiq.com/mockups/3184448.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

En suivant la logique de la disposition d'écriture (gauche-droite) de la version verticale, le compte-rendu le plus récent se retrouve ici en bas, ce qui s'écarte effectivement de la convention que l'on retrouve sur les blogs, mails, etc. Cette logique n'est pas forcément absurde puisqu'il ne s'agit pas d'éléments indépendants mais bien d'une chronologie dans la réflexion : on peut donc voir une certaine évolution en descendant dans les comptes-rendus. 

Si cela vous paraît plus logique, on peut toujours modifier la disposition afin d'avoir les comptes-rendus les plus récents en haut de la page; mais cette page étant une vue globale d'un journal, il ne me semble pas forcément très intuitif de "commencer la lecture" de la vue synthétique en bas de page.

**Comment by christophe-lejeune** [comment]
Merci pour la mise à jour des deux maquettes !

* Un détail : la maquette horizontale comporte des dates vraisemblables, mais pas la verticale. Je me rends compte que c'est ma faute : c'est la date de l'entretien avec Jean (et non pas Luc) qui devait être postposée. Mon conseil : sur la dernière maquette (verticale), datez l'entretien de Jean au 15/01/2014, puis reportez les dates de la maquette verticale sur la maquette horizontale. Enfin, vous auriez raison de me répondre que c'est vraiment du détail à ce stade. 

* Autre détail : l'exemple figurant sur les maquettes comporte des comptes rendus rédigés exclusivement en janvier. Les dates introduites dans le formulaire de recherche mériteraient peut-être de correspondre à cette période. 

* Je ne suis pas convaincu de l'opportunité de répéter la légende (code couleur) sur cette page. Par contre, j'aime bien l'idée que le survol d'une icône de couleur fasse apparaître son type. 

* La fonction de zoom est intéressante, mais pas obligatoire. Même sans implémentation d'un zoom, l'utilisateur peut circuler avec les ascenseurs voire également zoomer au niveau de l'affichage du navigateur. Ne pas l'implémenter allège l'interface (ainsi que le cahier des charges du développeur). 

Quant à choisir entre les deux présentations, je suis partagé : 
* Les flèches de la maquette verticale, allant en ligne droite, rendent le graphe plus lisible, plus clair. Par contre, en terme de maniabilité, la maquette verticale obligera à utiliser l'ascenceur horizontal pour se déplacer vers la droite au fur et à mesure que les entretiens sont conduits. Cela constitue un mode de scroll inhabituel dans un navigateur. 
* La maquette horizontale présente l'avantage de se conformer au sens de lecture (de gauche à droite et de haut en bas) et d'impliquer un scroll vers le bas (habituel sur le Web). Même si sa présentation semble plus "touffue" (notamment à cause des flèches courbées), j'aurais tendance à la préférer... pour autant que son implémentation ne coûte pas le double, bien entendu.
