### ISSUE TITLE
Unification des fonctionnalités

### ISSUE THREAD

**Issue by Slaals** [Hypertopic/Cassandre#56]
> Rédigé avec @valentinlefevre
# Introduction

Comme nous l'avions annoncé lors de la réunion avec @christophe-lejeune le 04/06, nous allons présenter les différents scénarii possibles avec les maquettes servant à la démonstration. Dans la mesure du possible, les scenarii se succèderont de manière logique.

Dans ce ticket on va tenter d'être le plus synthétique et clair possible pour ouvrir la discussion sur tous les scénarios, il va être très long.

Également nous avons pris l'initiative de proposer des solutions à différentes problématiques. Autant celles entendues lors des réunions que celles explicitement discutées dans les différents tickets. Évidemment aucune de nos suggestions ne fait office de solution parfaite ou fixe, mais il serait intéressant que ces différentes maquettes deviennent des modèles approuvés par le client. Donc des maquettes sur lesquels nous pourrons nous appuyer pour proposer de nouvelles fonctionnalités. C'est pourquoi à chaque remarque ou suggestion, les maquettes qui vont suivre seront éditées.
# Scenarii

---
### Lister les journaux de bord

![](https://utt.mybalsamiq.com/mockups/3204377.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)
- [x] La croix permet de supprimer le journal de bord, elle n'apparaît qu'au survole de la souris
- Clique sur le bouton "Nouveau journal"
### Créer un journal de bord

![](https://utt.mybalsamiq.com/mockups/3151186.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)
- Clique sur le bouton "Créer"

> Renvoie vers **Lister les journaux de bord**

---
## Affichage de la vue synthétique d'un journal de bord

> À partir de **Lister les journaux de bord**
- Double clique sur un journal de bord **("Locomotives")**
### Voir un journal de bord dans sa globalité

![](https://utt.mybalsamiq.com/mockups/3204402.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

---
## Consultation d'un compte-rendu

> À partir de **Voir un journal de bord dans sa globalité**
- Double clique sur un compte-rendu **("Table des propriétés")**
### Consulter un compte-rendu

![](https://utt.mybalsamiq.com/mockups/3205920.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

---
## Parcours dans les comptes-rendus

> À partir de **Consulter d'un compte rendu**
- Clique sur le bouton ![ufgfdg](https://cloud.githubusercontent.com/assets/7190343/8014526/f0eca1e4-0bd1-11e5-9e35-0f52bf1205a7.jpg)
### Lister les comptes-rendus qui s'appuient sur celui consulté

![](https://utt.mybalsamiq.com/mockups/3206043.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)
- Clique sur un compte-rendu **("Se préserver")**

> Renvoie vers **Consulter un compte-rendu**

---
## Création d'un compte-rendu à partir de la vue synthétique d'un journal de bord

> À partir de **Voir un journal de bord dans sa globalité**
- Clique sur le bouton "Créer un compte-rendu"
### Proposer les choix d'ancrages

![](https://utt.mybalsamiq.com/mockups/3204436.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)
- [x] L'utilisateur choisi le type de compte-rendu qu'il souhaite à partir de cette fenêtre
  - [x] Lorsqu'il change de type de compte-rendu souhaité, les propositions d'ancrages sont   actualisées
- [x] Les propositions sont séparées en deux parties afin d'assister le chercheur sur la "Gounded method theory". Il reste libre de choisir
- [x] Les comptes-rendus appaissent dans l'ordre d'apparation, la premier étant le plus récent
- Clique sur le bouton "Valider"
### Rédiger un compte-rendu

![](https://utt.mybalsamiq.com/mockups/3205785.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)
- Clique sur le bouton enregistrer

> Enregistre le compte-rendu et renvoie vers **Consulter un compte-rendu**

---
## Création d'un compte-rendu à partir d'une consultation d'un compte-rendu

> À partir de **Consulter un compte-rendu**
- Clique sur le bouton "Créer un compte-rendu"
### Proposer les choix d'ancrages

![](https://utt.mybalsamiq.com/mockups/3204358.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)
- [x] Le premier compte-rendu apparent est nativement coché et bloqué, l'utilisateur ayant lancé la création d'un nouveau compte-rendu depuis la consultation de ce compte-rendu choisi comme ancrage par défaut
- Clique sur le bouton "Valider"

> Renvoie vers **Rédiger un compte-rendu**

---
## Observation du flux sur un compte-rendu

> À partir de **Consulter un compte-rendu**
- Clique sur le bouton ![gfgf](https://cloud.githubusercontent.com/assets/7190343/8013891/8a052ff0-0bcc-11e5-868f-e6fb888e8375.png)
### Lister les flux

![](https://utt.mybalsamiq.com/mockups/3205118.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

**Comment by christophe-lejeune** [comment]
M'autorisez-vous à éditer votre billet initial pour corriger l'une ou l'autre formulation (sans changer la teneur du propos, évidemment) ? M'invitez vous à réagir dès maintenant ? Si oui, préférez-vous que je réagisse ici ou dans les billets relatifs aux différentes fonctionnalités ?

**Comment by Slaals** [comment]
Vous pouvez évidemment éditer le billet.

Pour les remarques, je pense que ce serait intéressant de les faire ici en faisant référence aux features concernées. Enfin, je pense que ça permettrait de centraliser le tout. Qui est l'objectif de ce billet.

**Comment by christophe-lejeune** [comment]
Bravo pour cet impressionnant travail d'unification. Ces scenarii sont stimulants ! 

Voici quelques remarques : 
### Lister les journaux de bord
Dans le ticket #52, @valentin-bonino évoque que « le système des pastilles ne convenait pas à tout le monde » et fait plusieurs propositions alternatives. Je viens d'y laisser un commentaire. 

### Créer un journal de bord
La fenêtre « Créer un journal de bord » ouvre un pop-up au dessus de la précédente. Dès lors, les boutons qui apparaissent dans la zone grisée devraient être les mêmes. 

### Consulter un compte-rendu
Cette maquette montre un compte-rendu (ici, une table des propriétés), assorti de ses commentaires (même si, ici, il n'y en a pas). Cette fenêtre est donc affichée du point de vue d'un participant au journal de bord, qui peut s'appuyer sur ce compte-rendu pour en créer un nouveau (via la bouton « Créer un compte-rendu ». Sauf erreur de ma part, le champ de saisie d'un commentaire n'a donc pas sa place ici, puisque seuls les invités saisissent de tels commentaires. 

### Lister les comptes-rendus qui s'appuient sur celui consulté
J'aime bien votre proposition permettant de « Lister les comptes-rendus qui s'appuient sur celui consulté ». 

### Rédiger un compte-rendu
Je remarque que vous avez choisi de conserver le bouton « Annuler » dont nous avions questionné l'utilité. Est-ce parce que cette question n'est pas encore tranchée ou parce que vous trouvez de bonnes raisons de le conserver ? 

Je reviens vers vous ultérieurement pour la suite. Excellente continuation d'ici là !

**Comment by Slaals** [comment]
> Dans le ticket #52, @valentin-bonino évoque que « le système des pastilles ne convenait pas à tout le monde » et fait plusieurs propositions alternatives. Je viens d'y laisser un commentaire. 

Ce sera une discussion qui sera faite en interne. En effet cela a été discuté mais aucune décision n'a été prise. Pour le bien de la présentation nous avons donc fait un choix arbitraire. De ce côté ce scénario verra probablement son apparance changée afin de convenir à une meilleure représentation. J'invite mes collègues qui travaillent sur le ticket #52 à participer à la discussion ou à directement modifier les maquettes correspondantes.

> La fenêtre « Créer un journal de bord » ouvre un pop-up au dessus de la précédente. Dès lors, les boutons qui apparaissent dans la zone grisée devraient être les mêmes. 

Modifié, merci de votre vigilance :) En effet nous avons été vraiment attentif à faire correspondre les maquettes... Et parfois des choses nous ont échappé !

> Sauf erreur de ma part, le champ de saisie d'un commentaire n'a donc pas sa place ici, puisque seuls les invités saisissent de tels commentaires. 

J'admets que les commentaires est une fonctionnalité, personnellement, que je n'ai pas trop suivie. Certainement, une information m'a échappé à ce sujet. Idem, ce sera discuté en interne et une modification sera apportée pour correspondre à ce qui a déjà été dit !

> Est-ce parce que cette question n'est pas encore tranchée ou parce que vous trouvez de bonnes raisons de le conserver ? 

Habitude d'informaticiens, nous avons mis ce bouton par réflexe ! Nous avons édité.

Merci de lister vos remarques, cela nous aide énormément !

En attendant la suite, bonne continuation à vous !

**Comment by christophe-lejeune** [comment]
Merci de cette impressionnante réactivité. Je poursuis donc, comme promis. 

## Consulter un compte-rendu
Je me demande ce qui est le plus parlant : « Éditer » ou « Modifier ». Je n'ai pas de certitude... Je soulève simplement la question. 

## Proposer les choix d'ancrages
La maquette proposée fonctionne bien pour nos exemples minimaux. Toutefois, dans une recherche réelle, il n'est pas rare que plus de 100 comptes-rendus soient disponibles. Dès lors, je propose de condenser l'affichage des comptes-rendus susceptibles d'êtres ajoutés comme ancrages. Pour ce faire, chaque compte-rendu ne devrait occuper qu'une ligne, avec sa date en regard. Le point de couleur indiquant le type, il n'est pas utile de le répéter.  

## Création d'un compte-rendu à partir d'une consultation d'un compte-rendu
Ouvrir la fenêtre des choix d'ancrages lorsque l'utilisateur demande la création d'un compte-rendu part d'une belle intention. Je pense toutefois que cela gênera celui ou celle qui, ayant une nouvelle idée, se décide à rédiger un nouveau compte-rendu. Mieux vaut lui donner directement accès à l'espace de rédaction. Il ou elle ajoutera des ancrages au besoin. Cela lui viendra assez naturellement grâce à l'affichage, à gauche, des ancrages. S'il ou elle a besoin d'avoir un compte-rendu sous les yeux pour rédiger sa dernière trouvaille, elle l'ajoutera comme ancrage... de la même manière que l'on feuillète son carnet papier pour se remémorer un compte-rendu antérieur. 

## Lister les flux
Vous proposez de lister tous les "flux" concernant un compte-rendu. C'est certes très complet mais je me demande si l'information pertinente ne risque pas de se noyer dans les autres. Les nombreuses consultations des membres de l'équipe sont, au final, secondaires, par rapport à l'historique des modifications et à la consultation par les invités. 

On pourrait objecter que mon argument ne vaut que lorsque tout va bien. En effet, dans une équipe de recherche dont les membres sont inégalement impliqués, traquer les consultations permettrait d'identifier un membre démissionnaire. Je reste cependant réservé sur l'intérêt de garder trace de toutes les consultations pour détecter un tel cas de figure. 

Enfin, la "cloche" est-elle l'icône habituelle pour renvoyer à un historique ?

Merci et excellente continuation à tous et toutes !!!

**Comment by valentinlefevre** [comment]
Bonjour nous allons tenter de répondre à tout ça.

>### Consulter un compte-rendu

>Je me demande ce qui est le plus parlant : « Éditer » ou « Modifier ». Je n'ai pas de certitude... Je soulève simplement la question.

"Modifier" est effectivement plus parlant et la maquette a été modifiée dans ce sens.

>### Proposer les choix d'ancrages

>La maquette proposée fonctionne bien pour nos exemples minimaux. Toutefois, dans une recherche réelle, il n'est pas rare que plus de 100 comptes-rendus soient disponibles. Dès lors, je propose de condenser l'affichage des comptes-rendus susceptibles d'êtres ajoutés comme ancrages. Pour ce faire, chaque compte-rendu ne devrait occuper qu'une ligne, avec sa date en regard. Le point de couleur indiquant le type, il n'est pas utile de le répéter.

Effectivement il y a une redondance d'information qui entraîne une déperdition de place dans la fenêtre, la maquette sera modifiée en ce sens.

>### Création d'un compte-rendu à partir d'une consultation d'un compte-rendu

>Ouvrir la fenêtre des choix d'ancrages lorsque l'utilisateur demande la création d'un compte-rendu part d'une belle intention. Je pense toutefois que cela gênera celui ou celle qui, ayant une nouvelle idée, se décide à rédiger un nouveau compte-rendu. Mieux vaut lui donner directement accès à l'espace de rédaction. Il ou elle ajoutera des ancrages au besoin. Cela lui viendra assez naturellement grâce à l'affichage, à gauche, des ancrages. S'il ou elle a besoin d'avoir un compte-rendu sous les yeux pour rédiger sa dernière trouvaille, elle l'ajoutera comme ancrage... de la même manière que l'on feuillette son carnet papier pour se remémorer un compte-rendu antérieur.

La fenêtre ouverte après un clic sur le bouton "Créer un compte-rendu" de la vue synthétique n'oblige pas la sélection d'un ancrage, elle n'oblige que la sélection d'un type de document, l'ancrage pouvant être ajouté durant l'édition comme vous le proposez. Il m'est difficile de voir en quoi cela pourrait être une gêne car dans le cadre de vos processus de création de compte-rendu il nous a été permis de constaté qu'il était particulièrement rare qu'un compte-rendu soit en dehors de tout contexte (sans ancrage, la réflexion menant à la rédaction du compte-rendu se base sur des réflexions antérieures décrites dans les précédents comptes-rendus sauf pour les comptes-rendus de terrain). La façon dont les idées apparaissent chez les uns et les autres étant particulièrement différentes il pourrait être gênant pour les personnes suivant le processus suivant : je relis les comptes-rendus précédents, une idée me vient en les lisant et je rédige un nouveau compte-rendu, de pouvoir donner rapidement corps aux "fondements" de leurs réflexions. Nous aborderons le sujet en groupe afin de prendre les points de vue des uns et des autres.


>### Lister les flux

>Vous proposez de lister tous les "flux" concernant un compte-rendu. C'est certes très complet mais je me demande si l'information pertinente ne risque pas de se noyer dans les autres. Les nombreuses consultations des membres de l'équipe sont, au final, secondaires, par rapport à l'historique des modifications et à la consultation par les invités.

Il serait donc important de rajouter la possibilité de filtrer ces flux : 
- les consultations, 
- les modifications, 
- les créations, 
- ...
afin de garde la possibilité d'avoir accès à toute l'information mais avant tout de pouvoir choisir quelle information nous semble la plus pertinente.

>On pourrait objecter que mon argument ne vaut que lorsque tout va bien. En effet, dans une équipe de recherche dont les membres sont inégalement impliqués, traquer les consultations permettrait d'identifier un membre démissionnaire. Je reste cependant réservé sur l'intérêt de garder trace de toutes les consultations pour détecter un tel cas de figure.

Ce point sera lui aussi aborder en groupe afin d'avoir les retours de chacun, une idée émergera peut être de ces échanges.

>Enfin, la "cloche" est-elle l'icône habituelle pour renvoyer à un historique ?

La cloche est un icône renvoyant régulièrement aux notifications, comme c'est le cas dans les outils Google, nous l'avons choisi arbitrairement mais il est tout à fait envisageable de le modifier si quelque chose de plus "générique" est proposé.

Bon dimanche

**Comment by christophe-lejeune** [comment]
### Création d'un compte-rendu à partir d'une consultation d'un compte-rendu
La solution adoptée me semble un peu trop "libérale" : lorsqu'il crée un compte-rendu à partir de la fenêtre de consultation d'un compte-rendu, l'utilisateur se voit suggéré un type de compte-rendu. Je ne trouve pas cela suffisamment didactique. Même si c'est plus de travail, je préconiserai que les fenêtres de consultation comportent des boutons de création de nouveaux comptes-rendus différents en fonction du type de compte-rendu consulté. 

Voici un tableau récapitulatif : 

Compte-rendu consulté | Compte-rendu s'appuyant sur le compte-rendu consulté
----|----
Terrain | Codage ; Terrain
Codage | Codage ; Théorique
Théorique | Théorique ; Opérationnel ; Table des propriétés
Opérationnel | Terrain ; Compte-rendu de scénario descriptif sur le déroulement de la recherche
Table des propriétés | Schématisation de codage axial
Schématisation de codage axial  | Schématisation globale 
Schématisation globale | Compte-rendu de scénario descriptif sur le vécu des acteurs
Compte-rendu de scénario descriptif sur le vécu des acteurs | Compte-rendu de scénario analytique

Attention : cette table ne recense pas tous les ancrages possibles (ceux-ci restant ajoutables via le pop-up que vous avez proposé). Elle indique simplement les types de comptes-rendus apparaissant dans le bouton de création (en bas à droite). J'espère ne rien oublier; n'hésitez pas à me rappeler à l'ordre si c'est le cas. 

Pour les mêmes raisons, je préconise de ne pas permettre la création de comptes-rendus à partir de l'affichage de la vue synthétique d'un journal de bord. Ainsi la création d'un compte-rendu passe nécessairement par la consultation d'un autre compte-rendu. Notez que cette solution est compatible avec les démarches ne pratiquant pas l'échantillonnage théorique, puisque tous les comptes-rendus de terrain peuvent être créés à partir du premier (qui découle pour sa part de la création du journal de bord). 

J'espère que ces suggestions sont claires et vous souhaite un mise en groupe efficace est productive. Bonne continuation !

**Comment by Slaals** [comment]
> J'espère ne rien oublier; n'hésitez pas à me rappeler à l'ordre si c'est le cas.

Votre remarque est très claire et est dans la continuité de cette volonté de rendre un outil didactique.

Cependant, j'ai le sentiment que cela affectera la liberté de l'utilisateur. En effet, nous avons vu en réunion qu'il était possible de procéder à la rédaction d'un compte-rendu théorique, par exemple, à partir d'un compte-rendu de terrain, et je pense qu'il y a plein d'autres cas similaires. Si on se fie à votre suggestion, il sera alors strictement impossible pour un utilisateur de rédiger un compte-rendu théorique sans avoir d'abord créé au préalable un compte-rendu de codage. On pourrait imaginer que la création d'un compte-rendu de codage vide suffit, puis à partir de ce compte-rendu vide créer le compte-rendu théorique, mais cela ne me semble pas parlant et donnerait un sentiment d'inachevé à l'utilisateur !

> je préconise de ne pas permettre la création de comptes-rendus à partir de l'affichage de la vue synthétique d'un journal de bord.

Est-il vraiment nécessaire de retirer cette possibilité à l'utilisateur ? Pouvez-vous être plus précis sur le problème que pose ce type de création ? Je vois cette possibilité comme une ouverture aux différentes méthodes de travail, et surtout comme un choix certain pour l'utilisateur sans surcharger l'interface.

**Comment by christophe-lejeune** [comment]
Cette plateforme poursuit bien le projet (didactique) de structurer le journal de bord au moyen de différents types de comptes-rendus. Ces différents types ont été définis il y a plusieurs dizaines d'années sans que les chercheurs se soient emparés de cette proposition. La logique qui veut que le compte-rendu de terrain constitue l'appui d'un compte-rendu de codage puis d'un compte-rendu théorique risque bien de ne plus apparaître à l'utilisateur si n'importe quel type peut être créé à partir de n'importe où. S'il faut bien faire preuve de souplesse (sinon, la plateforme risque de devenir inutilisable), le message sous-jacent doit, lui, bien être apparent. 

Il me semble que l'on arrive à un beau compromis en procédant comme suit : 
* La logique de succession des types de comptes-rendus apparaît clairement sur l'interface via le bouton de création d'un compte-rendu d'un autre type. 
* Une souplesse est accordée via le pop-up d'ajout d'ancrage permettant d'ajouter des ancrages d'un autre type. 

Ainsi, pour reprendre votre exemple, un compte-rendu théorique doit nécessairement être créé à partir d'un compte-rendu de codage. Je ne vois d'ailleurs pas de raison qu'il en soit autrement. Par contre, l'élaboration de ce compte-rendu théorique pourrait occasionner le rapprochement avec des comptes-rendus de terrain. Ceux-ci sont alors ajoutés via le pop-up d'ajout d'ancrage. Ainsi l'utilisateur s'imprègne de la logique et bénéficie néanmoins d'une certaine souplesse. Certes, ceci limite la liberté de l'utilisateur. Mais assouplir encore plus le modèle risque bien de déboucher sur des journaux de bord composés de cent comptes-rendus du même type, réalisés par des utilisateurs se demandant bien pourquoi les concepteurs ont conçu tous ces types aux noms tous les plus étranges que les autres. On manquerait alors notre objectif.

**Comment by christophe-lejeune** [comment]
Par rapport à sa première version, je viens d'éditer le tableau ci-dessus pour restreindre le nombre de possibilités (et ainsi le nombre de boutons à ajouter sur les maquettes).

**Comment by Slaals** [comment]
>Ainsi, pour reprendre votre exemple, un compte-rendu théorique doit nécessairement être créé à partir d'un compte-rendu de codage.

C'est bien enregistré, dans ce cas une modification sera apportée en conséquence !

**Comment by christophe-lejeune** [comment]
Deux options restent possibles quant à la création de comptes-rendus à partir de l'affichage de la vue synthétique d'un journal de bord : 
* Soit supprimer purement et simplement ce bouton (comme suggéré ci-dessus). La création d'un compte-rendu de terrain non planifié dans un compte-rendu opérationnel se réalise alors à partir d'un compte-rendu de terrain antérieur. Cette "astuce" est, à la réflexion, un peu étrange : les chercheurs ne planifient pas leurs passages sur le terrain ne conçoivent pas vraiment que les différentes observations de terrain dépendent les unes des autres.   
* Soit conserver ce bouton en le réservant exclusivement à la création d'un compte-rendu de terrain non planifié dans un compte-rendu opérationnel. Cette dernière option aurait peut-être le mérite d'alléger l'interface de la fenêtre du compte-rendu de terrain et, ce faisant, d'insister sur le rôle didactique de l'interface.

**Comment by supertinou** [comment]
- J'ai modifié la maquette qui n'était pas celle finalement décidé dans le ticket https://github.com/Hypertopic/Cassandre/issues/53.

- Voici un proposition pour la consultation des comptes-rendus avec :
   - l'affichage des ancrages sur le volet de gauche (avec en plus de de pouvoir consulter les ancrages parents, pouvoir consulter les ancrages enfants (ceux qui s'appuient sur le compte-rendu consulté) et comme il avait été proposé via l'icône représentant 3 lignes ainsi que de pouvoir ajouter des ancrages supplémentaires. Notez que je n'ai pas trouvé mieux que les termes enfants/parents, si vous avez des idées ? D'autre part, il est même possible de supprimer la légende en proposant l'affichage du type de compte-rendu au survol des minis icônes de comptes-rendus
    - la consultation du compte rendu au milieu avec les icônes (associé un tooltip descriptif) permettant de successivement :
         - 1) partager un compte-rendu
         - 2) voir l'historique d'activité (icône d'une horloge est plus adapté, il me semble, que l'icône d'une horloge représentant plutôt des notifications) 
         - 3) Accéder à menu de configuration / modification pour pouvoir peut être modifier le titre du compte-rendu, les ancrages,...
          - 4) Les icônes de mini compte-rendu de couleurs qui permettent de créer un compte rendu fils qui sera ancré à celui consulté. On retrouve ici un aspect pédagogique car l'utilisateur pourra de manière visuelle voir qu'elle sont les comptes-rendus qu'il est possible de rédiger en partant de celui lu.
    - Ajouter un commentaire si il est invité. 
 
*NB : Proposition de l'affichage du double ancrage à proposer dans  https://github.com/Hypertopic/Cassandre/issues/47*
 
Proposition :

![Conculter un compte rendu](https://utt.mybalsamiq.com/mockups/3176608.png?key=32178ee603e0f87bac6e519b360144e44b3e5116)

Maquette actuelle : 

![Conculter un compte rendu2](https://camo.githubusercontent.com/9bc8c5c196246262030dfd30833d7d8b6d0941fb/68747470733a2f2f7574742e6d7962616c73616d69712e636f6d2f6d6f636b7570732f333230353932302e706e673f6b65793d33323137386565363033653066383762616336653531396233363031343465343462336535313136)

**Comment by christophe-lejeune** [comment]
Merci @supertinou pour cette amélioration de la maquette. Même si nous n'allons pas la conserver telle quelle, c'est une très belle proposition. 

Voici ce que ça m'inspire. 
* L'horloge convient en effet bien mieux que la cloche. 
* Comme déjà signalé, le double champ de commentaires est inconsistant avec ce que nous avons convenu (une même personne ne peut pas être en même temps auteur d'un compte-rendu et invitée à commenter). 
* Le principe des icônes de couleur (en haut à droite) pour créer des comptes-rendus fonctionne bien. L'affichage en est ramassé et le + est parlant. Par contre (détail, peut-être), la présente proposition est inconsistante avec la version actuelle du tableau ci-dessus : seul un compte-rendu opérationnel (rouge) peut-être créé à partir d'un compte-rendu théorique. 
* Si je comprends bien, la roue dentée permet de passer dans un mode "édition" permettant notamment (je vous cite) modifier le titre ou les ancrages... mais ceci ne fait-il pas double emploi avec l'ajout d'ancrage déjà accessible via un bouton dédié ? Le bouton d'ajout d'ancrages est-il destiné à disparaître ?  
* Je ne suis pas convaincu par « parents » et « enfants ». Si cette terminologie pourrait tenir d'un point de vue logique, c'est une métaphore spatiale trompeuse : le parent est d'habitude au dessus et non en dessous. En fait, ce que vous appelez « parents » sont des ancrages. On pourrait à la rigueur parler d'« enracinements » (*grounding*, plongeant dans le sol) et de « feuilles ». Mais je ne suis pas sûr que nous ayons besoin d'une nouvelle terminologie : ancrage est bien suffisant. 
* Dans le panneau de gauche, les deux onglets (« parents » et « enfants ») présentent l'avantage d'alléger la maquette. Ils perdent cependant l'intention initiale : celle de visualiser le compte-rendu courant entre ceux sur lesquels il s'appuie (ses « enracinements », à gauche) et ceux qui s'appuient sur lui (ses « feuilles », à droite). Je crains donc que la présente proposition soit moins efficace pour situer le compte-rendu courant. Mais peut-être ai-je tord. Une alternative serait de prévoir un panneau à droite (comparable à celui de gauche), minimisé la plupart du temps mais qui apparaît à la demande (je suis bien conscient que cette proposition est très proche de la précédente)... Évidemment, je vous accorde que, avec des panneaux de tous les côtés, l'espace de rédaction risque de devenir congru... 
* Je crois qu'il est bon de garder la possibilité de déplier la prévisualisation des ancrages car, dans certains cas, l'utilisateur a besoin de les avoir sous les yeux lorsqu'il écrit le compte-rendu courant. Mais peut-être aviez-vous en tête de réserver cette option au mode "édition". 

Encore bravo pour le boulot accompli. Il en reste encore un peu. Merci et courage !

**Comment by valentinlefevre** [comment]
Concernant les points abordés plus haut :
>L'horloge convient en effet bien mieux que la cloche.

La signification d'un icône étant purement subjective nous modifierons l'icône pour mettre une horloge mais cela n'est toujours pas en parfaite adéquation avec la notion sous-jacente.

>Comme déjà signalé, le double champ de commentaires est inconsistant avec ce que nous avons convenu (une même personne ne peut pas être en même temps auteur d'un compte-rendu et invitée à commenter).

Nous avons pris en compte vos remarques, mais après avoir abordé le sujet en groupe il nous est apparu qu'un champs commentaire est pertinent en toute occasion et ne gène pas la lisibilité du compte-rendu pour les raisons suivantes :
- Les commentaires ont pour vocation de centraliser les échanges autour des comptes-rendus afin d'éviter la déperdition d'information (via facebook, mails, ...), en cela les laisser apporterait une réelle plus-value au projet,
- Les commentaires, comme présentés dans la maquette de @supertinou ne gène en rien la lisibilité du document car le panneau servant de conteneur est repliable,
- Afin d'offrir la possibilité à tous de pouvoir utiliser l'outil, le faire le plus générique possible, tout du moins pour les fonctionnalités les plus basiques nous paraît être la meilleure façon de faire.

>Si je comprends bien, la roue dentée permet de passer dans un mode "édition" permettant notamment (je vous cite) modifier le titre ou les ancrages... mais ceci ne fait-il pas double emploi avec l'ajout d'ancrage déjà accessible via un bouton dédié ? Le bouton d'ajout d'ancrages est-il destiné à disparaître ?

Encore une fois le choix des icônes peut prêter à confusion. Cependant concernant l'aspect modification, nous tenons à vous rappeler que la gestion des ancrages est une fonctionnalité à part entière qui n'a, selon nous, pas à être intégrée à l'édition d'un compte-rendu. Le bouton de modification des ancrages d'un compte-rendu est donc toujours accessible quelque soit le mode dans lequel se trouve le compte-rendu (édition ou consultation). La modification d'un compte-rendu se fait via la roue dentée.

>Je ne suis pas convaincu par « parents » et « enfants ». Si cette terminologie pourrait tenir d'un point de vue logique, c'est une métaphore spatiale trompeuse : le parent est d'habitude au dessus et non en dessous. En fait, ce que vous appelez « parents » sont des ancrages. On pourrait à la rigueur parler d'« enracinements » (grounding, plongeant dans le sol) et de « feuilles ». Mais je ne suis pas sûr que nous ayons besoin d'une nouvelle terminologie : ancrage est bien suffisant.

Nous abordons ici encore des questions de terminologie, nous trouvions le fait de faire la différence entre les comptes-rendus sur lequel est ancré le compte-rendu en question et les comptes-rendus qui sont ancrés sur le compte-rendu en question pertinente mais il est vrai que le vocabulaire peut être difficile à définir afin d'être le plus clair possible.

>Dans le panneau de gauche, les deux onglets (« parents » et « enfants ») présentent l'avantage d'alléger la maquette. Ils perdent cependant l'intention initiale : celle de visualiser le compte-rendu courant entre ceux sur lesquels il s'appuie (ses « enracinements », à gauche) et ceux qui s'appuient sur lui (ses « feuilles », à droite). Je crains donc que la présente proposition soit moins efficace pour situer le compte-rendu courant. Mais peut-être ai-je tord. Une alternative serait de prévoir un panneau à droite (comparable à celui de gauche), minimisé la plupart du temps mais qui apparaît à la demande (je suis bien conscient que cette proposition est très proche de la précédente)... Évidemment, je vous accorde que, avec des panneaux de tous les côtés, l'espace de rédaction risque de devenir congru...

On peut envisager que les éléments listés dans ce panneau soient cliquables et déployables afin d'avoir accès à plus d'informations, nous pensons ajouter une petite flèche symbolisant ceci dans la prochaine upgrade du mockup.

Nous espérons avoir répondu à la plus part de vos questionnements, les modifications seront certainement longues à venir car nous devons préparer le wiki afin de présenter le projet pour vendredi prochain.

**Comment by christophe-lejeune** [comment]
* Comme je vous l'avais annoncé, je présente le journal de bord au RIFReQ ce 17 juin 2015. Le [ texte de ma présentation est maintenant disponible](http://rifreq2015.sciencesconf.org/72727). 

* Je reste peu convaincu par la pertinence des fils de commentaires mais je respecte votre travail et le choix collectif qui en découle. Cela dit, ce choix semble suggérer deux structures parallèles : celle représentée dans la vue synthétique et celle des fils de commentaires apparaissant "sous" sous chaque compte-rendu (qui, eux, ne seront pas représentés dans la vue synthétique). 

  Pour l'exprimer autrement, votre choix de conserver des commentaires d'un troisième type dédouble l'existant et peut donner l'impression que vous n'avez pas compris qu'un compte-rendu qui s'appuie sur un autre est *toujours* déjà le "commentaire" du compte-rendu sur lequel il s'appuie. 

  Au final, peut-être que votre persistance à conserver un fil de commentaires indique votre propre insatisfaction de la vue synthétique à laquelle nous sommes arrivés ensemble. Peut-être fallait-il être moins graphique et utiliser une présentation indentée... 

* Quoi qu'il en soit, à quelques jours de la remise du projet, ces questions risquent bien de rester ouvertes... Elles pourraient cependant être discutées lors de votre présentation. Peut-être m'autoriserai-je d'en faire autant au RIFReQ.

* Point de détail : la fenêtre mentionnant les parents et les enfants se retrouve actuellement telle quelle dans le Wiki. S'il fallait la conserver (délai serré oblige), je préconise que vous remplaciez les parents par des "enracinements" et les enfants par des "feuilles".

**Comment by christophe-lejeune** [comment]
Cette réflexion sur les fils de commentaires suggèrent peut-être une solution au problème ergonomique soulevé à propos des comptes-rendus "feuilles" (ceux qui s'appuient sur le compte-rendu courant). Nous avons discuté de l'opportunité de les faire apparaître dans un panneau à droite ou à gauche. Peut-être le fil de commentaires suggéré nous indique une autre option : les faire apparaître sous le compte-rendu courant, à l'endroit du commentaire d'André Marvell sur la maquette actuelle.

**Comment by supertinou** [comment]
- Voici une proposition pour remplacer l'affichage des comptes-rendus feuilles du volet latéral gauche par un volet latéral droit pliable. Celui ci affiche les compte-rendus feuilles exactement comme les compte-rendus ancrées du volet latéral gauche. 
Celà ce rapproche de ce que nous avions discutés #57 avec les flêches et les menus qui dépassés de l'écran.
- Si cette alternative vous plait et que vous la validez, je mettrai à jours les maquettes pour refléter ces changements dans les tickets #57, #56 et dans le wiki avant la présentation de vendredi.

- *Notez que j'ai remplacé l'icone de roue crantée par l'icone d'un crayon pour le passage en mode édition. Cette icone me semble plus logique*
*Avec l'icone de roue crantée, je pensais surtout à un menu permettant de modifier quelques élements du compte-rendu, comme son nom ou d'autres chôses. (à voir si c'est utile)*

En espérant, @christophe-lejeune, que vous ayez un peu de temps pour réagir dessus.

![](http://cl.ly/image/2W013R1L043u/image.png)

**Comment by christophe-lejeune** [comment]
Bien que je ne sois pas totalement convaincu par « feuilles », il nous font boucler sans tarder. Je valide donc la maquette ci-dessus, moyennant deux dernières petites modifications. 
* Pour être consistant, je préconise de remplacer « Comptes rendus ancrés » par « Ancrages » (car ces comptes-rendus constituent les **ancrages** du compte-rendu courant).

  Si, en dépit de mon avis, vous vouliez conserver une expression mentionnant les « comptes-rendus » (avec trait d'union), pour maintenir la symétrie avec les « feuilles », je préférerais « Comptes-rendus racines ». Soyez cependant conscients de ce qu'impliquerait ce dernier choix (que je vous décourage de faire).
     * Ce choix romprait le lien avec le *Manuel d'analyse qualitative* (ce qui serait quant même gênant)
     * Il vous obligerait à renommer tous les éléments d'interface qui comportent le mot « ancrage » pour le remplacer par « racine ».

  Pour toutes ces raisons, « Ancrages » ne semble préférable. 
* Je vous invite également à vous coordonner avec @AndreMarvell pour que les tickets #40 et #45 soient consistants avec ce qui est proposé ici : la dernière version de la maquette du ticket #40, par exemple, ne tient actuellement pas compte des derniers développements exposés ci-dessus. 

Bon courage pour la dernière ligne droite !

**Comment by supertinou** [comment]
Très bien, merci beaucoup pour vos rapides retours!

Nous allons donc remplacer "Comptes rendus ancrées" par "Ancrages".
Peut être trouverons nous une alternative à l'expression "Comptes-rendus feuilles"

Merci, nous allons coordonner et unifier tout ça.
