### ISSUE TITLE
Organisation au niveau de la création du Wiki

### ISSUE THREAD

**Issue by PabloPrudhommeau** [Hypertopic/Cassandre#57]
Lors de la réunion avec le groupe de TP du vendredi, nous avons proposé un plan en ce qui concerne l'organisation des différentes parties que nous allons créer dans le Wiki. 
Nous pourrons ainsi nous appuyer sur ce Wiki pour la présentation du 19/06.
# Hiérarchie du Wiki proposée

_Chaque partie représente une nouvelle page du Wiki_
## Partie 1 : Introduction

Au sein de cette partie, nous parleront très rapidement de la « Grounded Theory Method » ou « Méthode d’Analyse Qualitative » pour planter le décor et nous enchaînerons sur la présentation synthétique du logiciel cassandre et de son contexte.
## Partie 2 : Navigation au sein du journal de bord

Cette partie a été placée juste après l'introduction pour permettre une meilleure compréhension de la plateforme avant de rentrer directement dans les détails.

La partie navigation présentera :
## Partie 3 : Gestion d'un journal de bord

Au sein de cette deuxième partie, nous présenterons toutes les fonctionnalités liées de près ou de loin à la création d'un journal de bord (ou "projet", c'est la même chose !).

Ceci inclut donc les fonctionnalités suivantes : 
#### Partager un journal de bord (https://github.com/Hypertopic/Cassandre/issues/53)

_Rappel : le partage d'un journal de bord ne se fait qu'entre les collaborateurs internes inscrits sur la plateforme. Si la personne n'a pas été ajoutée dans la liste des participant, celle-ci n'aura donc accès au journal de bord.
La fonctionnalité de partage d'un **compte rendu** sera quant à elle évoquée dans la Partie 4_ 
## NB

**Merci de vous référer au ticket https://github.com/Hypertopic/Cassandre/issues/56 qui présente l'ensemble des maquettes quoi qu'il en soit plus récentes que celles présentes dans les tickets mentionnés ci-dessus.**

@AndreMarvell @bj0rge @ChangruLU @ConstantSIDJUI @EdwardNjango @mchidaine @PabloPrudhommeau @salamata @Slaals @supertinou @valentin-bonino @valentinlefevre @yeahger

**Comment by bj0rge** [comment]
J'ai presque terminé la rédaction de la partie 4 (il reste un passage concernant les tables de propriétés, n'ayant pas travaillé dessus je préfèrerais que ce soit quelqu'un de plus proche du sujet qui la traite) rédigée avec @AndreMarvell.

Comme vu ce matin, nous nous sommes inspirés du [wiki du projet "Tire-a-part"](https://github.com/benel/Tire-a-part/wiki), mais j'ai peur que le contenu soit trop long, et donc peu lisible, quelqu'un a-t-il un avis à ce propos ? 

J'ai également créé la page d'accueil, centralisant toutes les pages que nous sommes en train de rédiger, [Manuel d'utilisation](https://github.com/Hypertopic/Cassandre/wiki/Manuel-d'utilisation). Je vous laisserai l'éditer pour mettre à jour les liens correspondants aux parties restantes (à savoir l'introduction générale et la gestion du journal de bord). Il n'y a plus qu'à l'alimenter !

Enfin, j'aimerais savoir comment vous préférez que nous nous organisions pour la présentation de ce vendredi. 

Bon weekend, 
Bastien

**Comment by valentinlefevre** [comment]
@bj0rge avec @Slaals on va peaufiner la partie 2 ce weekend, tout commentaire concernant la qualité et la forme du contenu est le bienvenu.

C'est vrai que notre wiki gagnerait à être le plus synthétique possible sans forcément n'être qu'une liste de fonctionnalités sans "âme". Mais ce n'est pas en une semaine que l'on pourrait atteindre ce résultat. Du coup afin de parer au plus pressé on pourrait voir ce wiki comme un support à la présentation de vendredi plutôt que comme un wiki "classique".

Pour la présentation de vendredi on ne pourra pas tous y prendre part, on est un peu plus d'une dizaine je crois ça commence à faire beaucoup, il faudrait que ceux que ça s'intéresse le disent. 3-4 personnes pour la présentation ce serait bien, une par partie. 

Bon weekend

**Comment by christophe-lejeune** [comment]
Je me permets de vous signaler que certaines maquettes utilisées dans le wiki ne comportent pas encore les modifications suggérées. C'est le cas notamment, mais pas seulement : 
* Aspect Collaboratif : Partager un compte-rendu : la maquette prévoit toute une série de modalités de partage que nous avions écartées.
* Les maquettes relatives aux schématisationx doivent encore être unifiées. Celle portant sur le codage sélectif nécessite encore plusieurs corrections pour être consistante avec ce qui a été discuté dans le ticket #49.
* Le panneau latéral de la fenêtre de consultation d'un compte-rendu fait l'objet de discussions (dans le ticket #56) qui mériteraient d'être prises en compte.

Bon courage pour la dernière ligne droite !

**Comment by PabloPrudhommeau** [comment]
@EdwardNjango, en ce qui concerne l'introduction, j'avais volontairement choisi d'être extrêmement concis pour que le lecteur saisisse instantanément le but de la méthode d'analyse qualitative de @christophe-lejeune sans directement rentrer dans des détails techniques. 

Dans l'optique où ta version soit définitivement validée, et quitte à être précis, je ne suis pas tout à fait d'accord avec certains éléments : 
* "Recherche Qualitative" est à mon sens beaucoup trop confus. L'expression "Méthode d'Analyse Qualitative" décrit à la fois l'aspect itératif que tu as mentionné, et également la notion d'étape (grâce au mot "méthode"). Le mot clef "analyse" me paraît également essentiel.
* Tu commences par décrire la "recherche qualitative" en soulignant ce qu'elle n'est pas. En effet, Il me semblerait moins maladroit de commencer par définir ce qu'elle est. La phrase en question est la suivante : 

> résultats produits ni par des procédures statistiques ni par d'autres moyens de quantification

* Tu as raison de dire que la méthode d'analyse qualitative est souvent utilisée, mais tu as oublié de parler de la "Grounded Theory Method" ou "Méthode de Théorisation Ancrée" qui elle est une méthode inédite, décrite, et utilisée par Cristophe Lejeune.
* Sans certitudes, je pense que l'expression "comprendre les acteurs en analysant leur vécu" est un peu trop restrictive. En effet, je pense qu'il serait plus pertinent de parler de la spécialité de Cristophe, à savoir l'éthnométhodologie et pourquoi pas la définir brièvement.

Merci à @EdwardNjango ou quiquonque ayant une objection à ces remarques, de réagir et nous permettre de finaliser l'introduction pour la présentation de vendredi.

**Comment by bj0rge** [comment]
@PabloPrudhommeau: Je suis d'accord avec toi, je pense que l'introduction doit être la plus synthétique possible dans la mesure où on explique plus en profondeur dans chacune des grandes parties lorsque c'est nécessaire.

**Comment by christophe-lejeune** [comment]
Je partage l'avis de @PabloPrudhommeau et @bj0rge. Celui ou celle qui voudrait savoir comment réaliser une recherche qualitative peut consulter le *Manuel d'analyse qualitative*. En résumer l'essence est audacieux et ne relève ni de votre cahier des charges, ni de votre formation. Je vous invite donc à privilégier les sections portant sur la présentation du journal de bord informatique.

NB: La *Grounded Theory Method* a été formalisée il y a une cinquantaine d'années par Barney Glaser et Anselm Strauss.

**Comment by EdwardNjango** [comment]
@PabloPrudhommeau je sois d'accord avec toi concernant l'expression "Méthode de recherche qualitative" et ta reformulation de la définition.

Par contre, je suis pas d'accord concernant la méthode de Théorisation Ancrée, je vois pas trop l'importance d'en parler puisqu'il s'agit d'un exemple de méthode de recherche qualitative faudrait pas oublier que Cassandre est un outil  d'analyse qualitative, il est destiné à faciliter  tout type de méthode de recherche qualitative et non pas seulement  la théorisation Ancrée. S'il faut mentioner la théorisation ancrée dans l'introduction il faut expliquer pourquoi (elle seule et pas les autres méthodes de recherche qualitative) , tu dis qu'elle est inédite mais pourtant elle est date des années 1960.

Pour le dernier point relatif à l'expression "comprendre les acteurs en analysant leur vécu"  il s'agit de décrire la méthode en de termes simples compréhensibles de tous.  Aussi  le simple fait que l’Ethnométhodologie soit la discipline de @christophe-lejeune  ne justifie pas qu'elle soit mentionnée dans l'introduction, c'est sa relation avec Cassandre qui nous  intéresse, je ne te comprends pas sur ce point.

**Comment by valentinlefevre** [comment]
Au risque de me répéter, nous n'avons toujours pas fixé une organisation à la présentation qui aura lieu vendredi matin et pour laquelle nous n'avons décidé ni de la liste des intervenants, ni du format de présentation (juste montrer le wiki me semble un peu pauvre mais avec le temps qu'il nous reste maintenant c'est la seule option).

**Comment by bj0rge** [comment]
Pour la présentation, @valentinlefevre et moi allons nous en occuper à moins que vous y voyiez quelque chose à redire.
Nous avons presque terminé les slides de présentation (ce sera bouclé demain matin), malheureusement il manque une partie de "*Gestion d'un journal de bord*" telle qu'elle l'a été définie par @PabloPrudhommeau (le partage avec des collaborateurs n'y est pas détaillé par exemple, de même que l'explication sur les trois types de CR initiaux qu'on peut avoir). @salamata et @valentin-bonino vous êtes les deux personnes à avoir travaillé sur cette page du wiki, pourriez-vous l'enrichir ? Ou même quelqu'un d'autre qui a réalisé les maquettes sur ce sujet.
Merci !

**Comment by christophe-lejeune** [comment]
Je vous souhaite, à toutes et tous, une excellente recette de projet ! 

@AndreMarvell @bj0rge @ChangruLU @ConstantSIDJUI @EdwardNjango @mchidaine @PabloPrudhommeau @salamata @Slaals @supertinou @valentin-bonino @valentinlefevre @yeahger

**Comment by valentinlefevre** [comment]
Merci beaucoup. Et de votre côté comment s'est passée la présentation?

**Comment by bj0rge** [comment]
Bonjour,
Vous trouverez ici [le document sur lequel nous nous sommes appuyés ](https://drive.google.com/file/d/0B5mL3E7iMCjKNDF5ZXkyMU9hZkU/view?usp=sharing) pour la présentation finale de la conception de Cassandre.

Je l'ajoute également sur le wiki.
