### ISSUE TITLE
Création d'un compte-rendu d'un type au choix (non défini par l'ancrage)

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#63]
Pour sa TX, @LouGrimal a besoin des mémos suivants : 

-  un mémo théorique pour le sujet de TX,
- deux ou trois mémos théoriques (éventuellement ancrés dans le premier) pour la bibliographie initiale. 

Comment fait-on pour créer les seconds ?

**Comment by christophe-lejeune** [comment]
Telle qu'elle est actuellement implémentée dans Cassandre, la logique du journal de bord tend à prévenir une telle création. 

C'est moins une limitation qu'une fonctionnalité : il s'agit d'amener l'utilisatrice à créer un compte-rendu opérationnel avant de se rendre en bibliothèque, ce pense-bête lui permettant également de se rappeler, au retour de la bibliothèque, pourquoi elle s'y est rendue... ce qui lui permet d'évaluer si les références trouvées répondent bien aux questions initialement posées. 

L'utilisatrice qui souhaiterait absolument contourner cette contrainte pourrait créer des comptes-rendus factices (**nécessairement munis d'un titre** temporaire). D'abord opérationnel (rouge), puis de terrain (gris), puis de codage (jaune). Ce dernier compte-rendu de codage peut servir de base à la création de plusieurs comptes-rendus théoriques. Il suffit ensuite de supprimer les comptes-rendus factices et d'ajouter aux derniers comptes-rendus théoriques un nouvel ancrage... à savoir le compte-rendu théorique originel. 

Ce contournement n'est ni très pratique ni très élégant mais cela permet d'obtenir le résultat escompté avec la version actuelle de la plateforme (donc sans nécessairement devoir solliciter puis attendre de nouveaux développements).

**Comment by LouGrimal** [comment]
Merci pour cet éclaircissement. Je peux à présent effectivement réaliser
plusieurs comptes-rendus théoriques.
Bien cordialement,
Lou Grimal

Le 14 mars 2017 à 16:14, Christophe Lejeune <notifications@github.com> a
écrit :
