### ISSUE TITLE
Formatage en MarkDown

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#64]
Un des mémos de @LouGrimal est en Markdown.
La liste et les sections apparaissent correctement, mais pas les paragraphes (pourtant ceux-ci sont bien séparés par deux retours à la ligne).

**Comment by christophe-lejeune** [comment]
Les marques de paragraphe exige qu'un espace soit inséré entre les deux retours à la ligne. Ce fonctionnement n'est certes pas très intuitif, mais c'est celui de la librairie mobilisée ([showdown](https://github.com/showdownjs/showdown)).

**Comment by christophe-lejeune** [comment]
Le comportement de cette librairie étant particulièrement contre-intuitif, j'ai modifié Cassandre pour que deux retours à la ligne soient automatiquement transformés de la manière attendue. Cette modification ne change rien à la manière dont le texte est enregistré dans la base de données, afin de ne pas créer de dépendance à la librairie actuellement utilisée. 

Merci de m'avoir signalé ce problème et, ce faisant, d'avoir contribué à l'amélioration de la plateforme.
