### ISSUE TITLE
Log the IP address of unregistered contributors

### ISSUE THREAD

**Issue by christophe-lejeune** [Hypertopic/Cassandre#66]
When a user is not registered, his-her modifications are logged with his-her IP address. Previously, this IP address was furnished `req.peer`. This used to work at the Université de Liège until recently. Currently `req.peer` returns local loop for any user (`127.0.0.1`). Data center and IT representatives were unable to explain the switch and argue it should come from Cassandre. 
However, another mechanism should be used in order for user's IP addresses to be recorded.

**Comment by benel** [comment]
It seems that your Data Center's reverse proxy changed its behaviour. Previously, it was correctly adding `X-Forwarded-For` directive and now it seems it does not anymore.

More information on https://httpd.apache.org/docs/current/mod/mod_proxy.html#x-headers
