### ISSUE TITLE
Uploading pictures in Field Memos

### ISSUE THREAD

**Issue by AlixHub** [Hypertopic/Cassandre#68]
So far, it is impossible to upload photographs or other pictures in field memos. It would be great to have this possibility as any picture taken on the field is a field memo.

**Comment by christophe-lejeune** [comment]
Indeed, (externally stored) images can be inserted in operational, coding, theoretical and storyline memos thanks to MarkDown syntax. As @AlixHub indicates, this is not possible for field memo... which is a pity given field memos needs it more than others !
It certainly would be useful to develop a dedicated feature allowing to attach a file (not only images, but perhaps also sounds or videos) to a memo. Such a feature may be integrated to Cassandre (files would be stored in Cassandre own database) or could rest on a shared service between Cassandre and [Steatite](/Hypertopic/Steatite) (files would then be stored in Steatite).

**Comment by christophe-lejeune** [comment]
This issue results from a broader one : current design regards field memo as transcripts. To bypass this limitation, users thus enter field notes as the first speech turn of an interview, which is not convenient. Experience definitely suggests to create an additional type of memos, dedicated to observation notes. Such a memo would behave just as operational, coding, theoretical or storyline memos. Among other features, it would thus allow to insert pictures. 

This new type of memo may be added as follows :
### Field memos
* [ ] As states above, the new type of memo would have the same design as others, and will be edited with the same template (`editable_memo`). 
* [ ] It will be identified with the gray icon currently used by field memos.
* [ ] As for current field memos, leaves than might be created from these field memos will be **coding** memos. 

### Transcripts
* [ ] Current field memo will be dedicated to transcripts. 
* [ ] Every call to 'field' memo will be converted into 'transcript' (including in the construction of the index used by the KWIC search feature).
* [ ] No change will be operated concerning leaves, edits (`editable_text`) and lexical features (rare, specific and repeated phrases). 
* [ ] A new icon will be assigned to these transcripts, evoking the speech turns of an interview.
