### ISSUE TITLE
Broken links to icons in documentation

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#90]
`http://www.cassandre.ulg.ac.be` refers (for example) to `https://github.com/Hypertopic/Cassandre/raw/master/_attachments/theoretical.png` which is now broken since PNG was replaced by SVG.

**Comment by christophe-lejeune** [comment]
Thank you very much for this warning. I have just updated the page. 

A similar update might be operated for the [hypertopic.org](https://hypertopic.org/cassandre) website to use the current SVG icons. Such an update could be performed either by updating the website SVG files or by inserting hyperlinks pointing directly to Cassandre code repository (as I have done for `http://www.cassandre.ulg.ac.be/`).

**Comment by benel** [comment]
> A similar update might be operated for the hypertopic.org website to use the current SVG icons. 

OK, it's done : https://hypertopic.org/cassandre

Note: I've changed also the text by replacing "color code" with "pictogram". A similar update might be necessary in Cassandre.

**Comment by christophe-lejeune** [comment]
Thank you for the suggestion. "Color code" is now replaced with "pictograms".
