### ISSUE TITLE
Duplicate checkbox on memo deletion

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#92]
Same problem in english and french localization:
<img width="464" alt="Capture d’écran 2019-09-02 à 18 26 37" src="https://user-images.githubusercontent.com/597307/64126848-aef87480-cdaf-11e9-9817-b8573bb34206.png">
<img width="317" alt="Capture d’écran 2019-09-02 à 18 28 28" src="https://user-images.githubusercontent.com/597307/64126856-b1f36500-cdaf-11e9-926c-77e3fd442fbd.png">

**Comment by christophe-lejeune** [comment]
This is a known issue, due to code being tested during the deep refactorization ongoing this summer. This will be fixed with the new code for the diary page (deeply rewritten).

**Comment by benel** [comment]
Duplication seems to be fixed (at least in branch `refactoring-process`).
