### ISSUE TITLE
Memo page should not be reloaded every minute

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#94]
While a mere problem _per se_ (just a small waste of resources), the page reload by Cassandre makes LaSuli to reload its sidebar and to loose the user's visual context, making the annotation process very painful.

The reason for this cyclic reload is that:
1. CouchDB longpoll changes feed has a default `timeout` and `hearbeat` of 60,000 ms.
2. Cassandre code made no difference between a response containing changes and an empty response due to the timeout/heartbeat.

**Comment by benel** [comment]
@christophe-lejeune A fix has been implemented in 
a2820fa (that you can cherrypick in your own branch or merge later if you prefer).

**Comment by christophe-lejeune** [comment]
Another strategy may (perhaps) consists in modifying CouchDB filter, without modifying the Ajax longpoll request. Do you consider both strategy are equivalent ? Or one strategy is likely more efficient/light/fast than another ?

**Comment by benel** [comment]
> Another strategy may (perhaps) consists in modifying CouchDB filter, without modifying the Ajax longpoll request. 

Changing the filter would not change anything. An alternate strategy could have been to change the default parameters of CouchDB but: 
-  it would make CouchDB installation more difficult, 
- moreover it is not possible since 60s is already the max,
- the same problem would occur after X seconds (X being the new heartbeat).

There is indeed an algorithmic error in the initial code: it only handles the case where an update occurs, and not the case when no updates come before the timeout.

The correct algorithm (corresponding to my fix) is the following:

    wait for changes
    IF changes occurs THEN reload the page
    wait again (on timeout)

to be compared with the initial code:

    wait for changes
    reload (both on changes and timeout)

Don't hesitate to ask more details if it is not clear.

**Comment by christophe-lejeune** [comment]
Thank you for your prompt explanation. I will cherrypick your code for memo and diary ;-)
